Repository jenkins-x/lighthouse, pull requests merged in 2019-08, with the labels that each got.

#65 chore: upgrade to latest go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#66 fix: lets allow nested paths within the webhook URLs
  go.mod
  go.sum
  pkg/webhook/webhook.go
Labels: approved, size/S

#67 chore: upgrade to latest go-scm
  go.mod
  go.sum
  pkg/webhook/webhook.go
Labels: approved, size/XS

#68 chore: upgrade to latest go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#75 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#76 chore: upgrade go-scm and jx
  go.mod
  go.sum
Labels: approved, size/XS

#84 fix: upgrade git version
  Dockerfile
Labels: approved, size/S

#89 fix: upgrade git version
  Dockerfile
Labels: approved, size/XS

#90 fix: refactor PlumberJob
  pkg/plumber/constants.go
  pkg/plumber/fake/fake.go
  pkg/plumber/interface.go
  pkg/plumber/plumber.go
  pkg/plumber/types.go
  pkg/prow/config/config.go
  pkg/prow/config/jobs.go
  pkg/prow/config/tide.go
  pkg/prow/pjutil/filter.go
  pkg/prow/pjutil/pjutil.go
  pkg/prow/pjutil/pjutil_test.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/plugins/trigger/pull-request_test.go
  pkg/prow/plugins/trigger/push_test.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/trigger/trigger_test.go
Labels: approved, size/XL

#95 fix: bump lighthouse image tag in chart
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#96 fix: upgrade jx version
  charts/lighthouse/templates/deployment.yaml
  go.mod
  go.sum
Labels: approved, size/S

#97 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/M

#98 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#99 chore: enable the lint and security lint, fix the warnings and reorganised the pipeline file
  Makefile
  jenkins-x.yml
  pkg/caches/resource_cache.go
  pkg/caches/sourcerepo_cache.go
  pkg/cmd/helper/error.go
  pkg/plumber/fake/fake.go
  pkg/plumber/plumber.go
  pkg/plumber/types.go
  pkg/prow/config/branch_protection.go
  pkg/prow/config/branch_protection_test.go
  pkg/prow/config/config.go
  pkg/prow/config/config_test.go
  pkg/prow/config/jobs.go
  pkg/prow/config/secret/secret.go
  pkg/prow/git/git.go
  pkg/prow/git/localgit/localgit.go
  pkg/prow/github/client.go
  pkg/prow/github/content.go
  pkg/prow/github/git.go
  pkg/prow/github/issues.go
  pkg/prow/github/legacy_helpers.go
  pkg/prow/github/organizations.go
  pkg/prow/github/pull_requests.go
  pkg/prow/github/repositories.go
  pkg/prow/github/reviews.go
  pkg/prow/github/test_helpers.go
  pkg/prow/hook/events.go
  pkg/prow/pjutil/filter.go
  pkg/prow/plugins/approve/approve_test.go
  pkg/prow/plugins/cat/cat.go
  pkg/prow/plugins/config.go
  pkg/prow/plugins/lgtm/lgtm_test.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/repoowners/repoowners.go
  pkg/watcher/configmap_watcher.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#101 chore: cleanup some dead code and code which was commented out
  pkg/caches/environment_cache.go
  pkg/caches/helpers.go
  pkg/caches/resource_cache.go
  pkg/caches/schedule_cache.go
  pkg/caches/sourcerepo_cache.go
  pkg/main/main.go
  pkg/plumber/plumber.go
  pkg/prow/hook/events.go
  pkg/prow/hook/plugins.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/XL

#100 fix: switch the docker image to use alpine and cleanup the makefile
  Dockerfile
  Makefile
  charts/lighthouse/.helmignore
  charts/lighthouse/Makefile
  charts/lighthouse/README.md
  charts/lighthouse/templates/NOTES.txt
  charts/lighthouse/templates/_helpers.tpl
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/ksvc.yaml
  charts/lighthouse/templates/service.yaml
  charts/lighthouse/values.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  go.sum
  jenkins-x.yml
Labels: approved, lgtm, size/M

#105 fix: Switch to metapipeline client
  go.mod
  go.sum
  pkg/plumber/fake/fake.go
  pkg/plumber/interface.go
  pkg/plumber/plumber.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/trigger/push.go
  pkg/prow/plugins/trigger/trigger.go
Labels: approved, size/L
