Repository jenkins-x/lighthouse, pull requests merged in 2019-10, with the labels that each got.

#246 fix: add support for ping
  pkg/prow/logrusutil/logrusutil.go
  pkg/webhook/webhook.go
Labels: approved, size/S

#252 fix: minor refactor to make the code easier to reuse
  go.mod
  go.sum
  pkg/webhook/webhook.go
Labels: approved, size/L

#256 fix: use the lighthouse servers factory to create metapipeline clients
  pkg/plumber/helpers.go
  pkg/prow/hook/events.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/plugins.go
  pkg/webhook/webhook.go
Labels: approved, size/M

#262 fix: to avoid metaclient creation failure
  Dockerfile
  go.mod
  go.sum
  pkg/plumber/helpers.go
  pkg/prow/plugins/plugins.go
  pkg/webhook/webhook.go
Labels: approved, size/M

#272 fix: add updatebot.sh script
  updatebot.sh
Labels: approved, size/XS

#275 fix: switch to building the binaries in the build pod
  Dockerfile
  Dockerfile.tide
  jenkins-x.yml
Labels: approved, size/M

#273 fix: add updatebot step after release
  jenkins-x.yml
Labels: approved, size/XS

#276 fix: lets try to eagerly create metapipeline clients
  pkg/plumber/helpers.go
  pkg/prow/hook/events.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/plugins.go
  pkg/webhook/webhook.go
Labels: approved, size/M

#277 fix: fix up the pipeline
  jenkins-x.yml
Labels: approved, size/XS

#278 fix: updatebot PR creation
  updatebot.sh
Labels: approved, size/XS

#279 chore: Remove @dwnusbaum from OWNERS
  OWNERS
Labels: approved, lgtm, size/XS
