Repository jenkins-x/lighthouse, pull requests merged in 2019-09, with the labels that each got.

#106 chore: upgrade go-scm
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#107 fix: Get chartmuseum password, not just user
  jenkins-x.yml
Labels: approved, lgtm, size/S

#113 chore(deps): bump https://github.com/jenkins-x/go-scm from v1.5.25 to 1.5.26
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  go.mod
  go.sum
Labels: size/S, updatebot

#116 fix: add checksum for secret
  Makefile
  charts/lighthouse/templates/deployment.yaml
Labels: size/XS

#166 fix: use better liveness probe
  charts/lighthouse/templates/tide-deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/S
