Repository jenkins-x/lighthouse, pull requests merged in 2019-07, with the labels that each got.

#9 fix: pipeline
  Dockerfile
  Makefile
  jenkins-x.yml
Labels: size/M

#15 Rearranging a few things
  Dockerfile
  Makefile
  README.md
  charts/catcher/.helmignore
  charts/catcher/Chart.yaml
  charts/catcher/Makefile
  charts/catcher/README.md
  charts/catcher/templates/NOTES.txt
  charts/catcher/templates/_helpers.tpl
  charts/catcher/templates/deployment.yaml
  charts/catcher/templates/ksvc.yaml
  charts/catcher/templates/service.yaml
  charts/catcher/values.yaml
  cmd/catcher/main.go
  go.mod
  go.sum
  pkg/builder/builder.go
  pkg/builder/interface.go
  pkg/caches/resource_cache.go
  pkg/caches/sourcerepo_cache.go
  pkg/cmd/common.go
  pkg/cmd/helper/error.go
  pkg/cmd/webhook.go
  pkg/git/bitbucketserver/client.go
  pkg/git/bitbucketserver/webhook.go
  pkg/git/interface.go
  pkg/main/main.go
Labels: size/XXL

#16 Some package rearranging, Webhook CRD
  deployments/charts/catcher/.helmignore
  deployments/charts/catcher/Chart.yaml
  deployments/charts/catcher/Makefile
  deployments/charts/catcher/README.md
  deployments/charts/catcher/templates/NOTES.txt
  deployments/charts/catcher/templates/_helpers.tpl
  deployments/charts/catcher/templates/deployment.yaml
  deployments/charts/catcher/templates/ksvc.yaml
  deployments/charts/catcher/templates/service.yaml
  deployments/charts/catcher/values.yaml
  deployments/charts/preview/Chart.yaml
  deployments/charts/preview/Makefile
  deployments/charts/preview/requirements.yaml
  deployments/charts/preview/values.yaml
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/doc.go
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/doc.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_webhook.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/webhook.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/jenkins.io/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/webhook.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/webhook.go
  pkg/git/bitbucketserver/client.go
  pkg/git/interface.go
Labels: size/XXL

#19 Added CRD manifest, fixed issues with webhook creation
  cmd/webhook/main.go
  deployments/manifests/000-namespace.yaml
  deployments/manifests/100-webhook-crd.yaml
  deployments/manifests/200-webhook-deployment.yaml
  deployments/manifests/300-webhook-service.yaml
  deployments/manifests/400-webhook-ingress.yaml
  deployments/manifests/600-rolebinding.yaml
  pkg/git/bitbucketserver/client.go
Labels: size/M

#21 fix: updated Dockerfile with new make target
  Dockerfile
  VERSION
  deployments/charts/webhook/.helmignore
  deployments/charts/webhook/Chart.yaml
  deployments/charts/webhook/Makefile
  deployments/charts/webhook/README.md
  deployments/charts/webhook/templates/NOTES.txt
  deployments/charts/webhook/templates/_helpers.tpl
  deployments/charts/webhook/templates/deployment.yaml
  deployments/charts/webhook/templates/ksvc.yaml
  deployments/charts/webhook/templates/service.yaml
  deployments/charts/webhook/values.yaml
  jenkins-x.yml
Labels: size/M

#22 Revert "fix: updated Dockerfile with new make target"
  Dockerfile
  VERSION
  deployments/charts/catcher/.helmignore
  deployments/charts/catcher/Chart.yaml
  deployments/charts/catcher/Makefile
  deployments/charts/catcher/README.md
  deployments/charts/catcher/templates/NOTES.txt
  deployments/charts/catcher/templates/_helpers.tpl
  deployments/charts/catcher/templates/deployment.yaml
  deployments/charts/catcher/templates/ksvc.yaml
  deployments/charts/catcher/templates/service.yaml
  deployments/charts/catcher/values.yaml
  jenkins-x.yml
Labels: size/M

#23 Revert "Added CRD manifest, fixed issues with webhook creation"
  cmd/webhook/main.go
  deployments/manifests/100-namespace.yaml
  deployments/manifests/100-webhook-crd.yaml
  deployments/manifests/200-webhook.yaml
  deployments/manifests/300-service.yaml
  deployments/manifests/400-ingress.yaml
  deployments/manifests/600-rolebinding.yaml
  pkg/git/bitbucketserver/client.go
Labels: size/M

#24 Revert "feat: renamed catcher to webhook"
  Makefile
  README.md
  cmd/catcher/main.go
  deployments/manifests/200-catcher.yaml
  deployments/manifests/300-service.yaml
  deployments/manifests/400-ingress.yaml
  deployments/manifests/600-clusterrolebinding.yaml
Labels: size/M

#25 Revert "Updates to build, Bitbucket Server provider, webhook CRD"
  README.md
  cmd/catcher/main.go
  deployments/manifests/100-namespace.yaml
  deployments/manifests/200-catcher.yaml
  deployments/manifests/300-service.yaml
  deployments/manifests/400-ingress.yaml
  deployments/manifests/500-clusterrole.yaml
  deployments/manifests/600-clusterrolebinding.yaml
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/doc.go
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_webhook.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/webhook.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/jenkins.io/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/webhook.go
  pkg/git/bitbucketserver/client.go
Labels: size/L

#26 Revert "Some package rearranging, Webhook CRD"
  charts/catcher/.helmignore
  charts/catcher/Chart.yaml
  charts/catcher/Makefile
  charts/catcher/README.md
  charts/catcher/templates/NOTES.txt
  charts/catcher/templates/_helpers.tpl
  charts/catcher/templates/deployment.yaml
  charts/catcher/templates/ksvc.yaml
  charts/catcher/templates/service.yaml
  charts/catcher/values.yaml
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  go.mod
  go.sum
  pkg/apis/jenkins.io/v1/doc.go
  pkg/apis/jenkins.io/v1/register.go
  pkg/apis/jenkins.io/v1/types.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/doc.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/doc.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/doc.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/fake/fake_webhook.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/jenkins.io_client.go
  pkg/client/clientset/versioned/typed/jenkins.io/v1/webhook.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client/informers/externalversions/jenkins.io/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/interface.go
  pkg/client/informers/externalversions/jenkins.io/v1/webhook.go
  pkg/client/listers/jenkins.io/v1/expansion_generated.go
  pkg/client/listers/jenkins.io/v1/webhook.go
  pkg/git/bitbucketserver/client.go
  pkg/git/interface.go
Labels: size/XXL

#27 Revert "Rearranging a few things"
  Dockerfile
  Makefile
  README.md
  charts/lighthouse/.helmignore
  charts/lighthouse/Chart.yaml
  charts/lighthouse/Makefile
  charts/lighthouse/README.md
  charts/lighthouse/templates/NOTES.txt
  charts/lighthouse/templates/_helpers.tpl
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/ksvc.yaml
  charts/lighthouse/templates/service.yaml
  charts/lighthouse/values.yaml
  cmd/catcher/main.go
  go.mod
  go.sum
  pkg/builder/builder.go
  pkg/builder/interface.go
  pkg/caches/resource_cache.go
  pkg/caches/sourcerepo_cache.go
  pkg/cmd/common.go
  pkg/cmd/helper/error.go
  pkg/cmd/webhook.go
  pkg/git/bitbucketserver/client.go
  pkg/git/bitbucketserver/webhook.go
  pkg/git/interface.go
  pkg/main/main.go
Labels: size/XXL

#29 feat: improved support for Bitbucket Server
  cmd/webhook/main.go
  pkg/apis/jenkins.io/v1/types.go
  pkg/apis/jenkins.io/v1/zz_generated.deepcopy.go
  pkg/git/bitbucketserver/client.go
  pkg/git/bitbucketserver/webhook.go
Labels: size/L

#32 fix: migrated the lgtm plugin and tests over to the go-scm provider
  README.md
  go.mod
  go.sum
  pkg/prow/fakegithub/fakegithub.go
  pkg/prow/github/client.go
  pkg/prow/plugins/approve/approve_test.go
  pkg/prow/plugins/approve/approvers/owners.go
  pkg/prow/plugins/lgtm/lgtm.go
  pkg/prow/plugins/lgtm/lgtm_test.go
  pkg/prow/plugins/milestone/milestone.go
  pkg/prow/plugins/milestonestatus/milestonestatus.go
Labels: approved, size/L

#33 add working prow plugins
  README.md
  go.mod
  go.sum
  pkg/cmd/webhook.go
  pkg/main/main.go
  pkg/prow/github/client.go
  pkg/prow/plugins/approve/approve_test.go
  pkg/prow/plugins/blockade/blockade_test.go
  pkg/prow/plugins/branchcleaner/branchcleaner_test.go
  pkg/prow/plugins/cat/cat_test.go
  pkg/prow/plugins/dog/dog_test.go
  pkg/prow/plugins/help/help_test.go
  pkg/prow/plugins/hold/hold_test.go
  pkg/prow/plugins/label/label_test.go
  pkg/prow/plugins/lgtm/lgtm_test.go
  pkg/prow/plugins/owners-label/owners-label_test.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/pony/pony_test.go
  pkg/prow/plugins/shrug/shurg_test.go
  pkg/prow/plugins/wip/wip-label_test.go
  pkg/prow/plugins/yuks/yuks_test.go
  pkg/prow/repoowners/repoowners.go
Labels: size/L

#34 fix: load configuration from the ConfigMaps
  README.md
  pkg/builder/builder.go
  pkg/builder/interface.go
  pkg/caches/environment_cache.go
  pkg/caches/helpers.go
  pkg/caches/resource_cache.go
  pkg/caches/schedule_cache.go
  pkg/caches/sourcerepo_cache.go
  pkg/cmd/common.go
  pkg/cmd/webhook.go
  pkg/prow/config/config.go
  pkg/prow/hook/events.go
  pkg/prow/plugins/config.go
Labels: size/L

#35 fix: use simpler CLI
  Dockerfile
Labels: size/XS

#36 fix: use GIT_TOKEN env var to simplify setup
  README.md
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/values.yaml
  pkg/cmd/webhook.go
  pkg/prow/github/github_helpers.go
Labels: size/M

#37 fix: add git to docker and volume mount the prow config
  Dockerfile
  charts/lighthouse/templates/deployment.yaml
Labels: size/S

#39 use correct env vars when publishing chart
  charts/lighthouse/Makefile
Labels: size/XS

#40 fix: use correct env vars when publishing chart again
  charts/lighthouse/Makefile
Labels: approved, size/XS

#38 fix: upgrade to latest jx
  README.md
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/role.yaml
  charts/lighthouse/templates/rolebinding.yaml
  charts/lighthouse/templates/serviceaccount.yaml
  charts/lighthouse/values.yaml
  go.mod
  go.sum
  pkg/builder/builder.go
  pkg/builder/interface.go
  pkg/main/main.go
  pkg/plumber/constants.go
  pkg/plumber/interface.go
  pkg/plumber/plumber.go
  pkg/plumber/types.go
  pkg/prow/config/config.go
  pkg/prow/config/config_test.go
  pkg/prow/config/jobs.go
  pkg/prow/fakegithub/fakegithub.go
  pkg/prow/github/client.go
  pkg/prow/github/git.go
  pkg/prow/github/issues.go
  pkg/prow/github/legacy_helpers.go
  pkg/prow/github/organizations.go
  pkg/prow/github/pull_requests.go
  pkg/prow/github/repositories.go
  pkg/prow/github/reviews.go
  pkg/prow/github/test_helpers.go
  pkg/prow/hook/events.go
  pkg/prow/hook/plugins.go
  pkg/prow/pjutil/filter_test.go
  pkg/prow/pjutil/pjutil.go
  pkg/prow/pjutil/pjutil_test.go
  pkg/prow/plugins/config.go
  pkg/prow/plugins/lifecycle/close.go
  pkg/prow/plugins/lifecycle/close_test.go
  pkg/prow/plugins/lifecycle/lifecycle.go
  pkg/prow/plugins/lifecycle/lifecycle_test.go
  pkg/prow/plugins/lifecycle/reopen.go
  pkg/prow/plugins/lifecycle/reopen_test.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/skip/skip.go
  pkg/prow/plugins/skip/skip_test.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/plugins/trigger/pull-request.go
  pkg/prow/plugins/trigger/pull-request_test.go
  pkg/prow/plugins/trigger/push.go
  pkg/prow/plugins/trigger/push_test.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/trigger/trigger_test.go
  pkg/webhook/webhook.go
Labels: size/XXL

#42 enable unit tests
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  jenkins-x.yml
  pkg/plumber/constants.go
  pkg/plumber/fake/fake.go
  pkg/prow/config/config.go
  pkg/prow/config/config_test.go
  pkg/prow/config/jobtests/job_config_test.go
  pkg/prow/pjutil/filter_test.go
  pkg/prow/pjutil/pjutil.go
  pkg/prow/pjutil/pjutil_test.go
  pkg/prow/plugins/config.go
  pkg/prow/plugins/lifecycle/close_test.go
  pkg/prow/plugins/lifecycle/lifecycle_test.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/skip/skip.go
  pkg/prow/plugins/skip/skip_test.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/plugins/trigger/pull-request_test.go
  pkg/prow/plugins/trigger/push.go
  pkg/prow/plugins/trigger/push_test.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/trigger/trigger_test.go
  pkg/webhook/webhook.go
Labels: size/XXL

#43 fix: use the correct docker org
  charts/lighthouse/templates/hmacsecret.yaml
  charts/lighthouse/values.yaml
  jenkins-x.yml
  skaffold.yaml
Labels: size/S

#44 fix: add support for `lighthouse --version`
  Makefile
  pkg/main/main.go
  pkg/version/info.go
Labels: size/M

#45 fix: add --verion support
  Dockerfile
  jenkins-x.yml
  pkg/webhook/webhook.go
Labels: size/S

#46 fix: tidied up the wait group handling
  pkg/prow/config/config.go
  pkg/prow/hook/events.go
  pkg/webhook/webhook.go
Labels: approved, size/S

#47 fix: lets watch the ConfigMaps directly for configuration changes
  README.md
  charts/lighthouse/templates/deployment.yaml
  pkg/prow/config/config.go
  pkg/prow/github/client.go
  pkg/prow/plugins/plugins.go
  pkg/watcher/configmap_watcher.go
  pkg/webhook/webhook.go
Labels: approved, size/L

#48 fix: possible NPE
  pkg/prow/config/jobs.go
Labels: approved, size/XS

#49 fix: another NPE
  pkg/prow/config/jobs.go
Labels: approved, size/XS

#50 fix: bug loading configurations from config maps
  pkg/prow/config/jobs.go
Labels: approved, size/S

#52 fix: possible NPE
  pkg/prow/config/jobs.go
  pkg/prow/hook/events.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/webhook/webhook.go
Labels: size/L

#53 fix: implement GetFile on the prow github interface
  pkg/prow/github/client.go
  pkg/prow/github/content.go
Labels: approved, size/S

#54 fix: fixes for GitHub Enterprise
  go.mod
  go.sum
  pkg/prow/genfiles/genfiles.go
  pkg/prow/git/git.go
  pkg/prow/git/localgit/localgit.go
  pkg/prow/gitattributes/gitattributes.go
  pkg/prow/plugins/size/size_test.go
  pkg/webhook/webhook.go
Labels: approved, size/M

#55 chore: latest go-scm
  go.mod
  go.sum
Labels: approved, size/XS

#56 fix: handle bitbucket server Namespaces better
  go.mod
  go.sum
  pkg/prow/config/config.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/skip/skip.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/pull-request.go
  pkg/prow/plugins/trigger/push.go
Labels: approved, size/M

#57 chore: upgrade jx
  go.mod
  go.sum
Labels: approved, size/XS

#58 fix: patch roles so lighthouse can lazily modify the dev env
  charts/lighthouse/templates/role.yaml
Labels: approved, size/XS

#62 fix: fixed PRs on bitbucket server
  go.mod
  go.sum
  pkg/prow/fakegithub/fakegithub.go
  pkg/prow/git/git.go
  pkg/prow/git/localgit/localgit.go
  pkg/prow/github/issues.go
  pkg/prow/github/repositories.go
  pkg/prow/hook/events.go
  pkg/prow/plugins/approve/approve.go
  pkg/prow/plugins/assign/assign.go
  pkg/prow/plugins/assign/assign_test.go
  pkg/prow/plugins/blockade/blockade.go
  pkg/prow/plugins/cat/cat.go
  pkg/prow/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/prow/plugins/cherrypickunapproved/cherrypick-unapproved_test.go
  pkg/prow/plugins/dog/dog.go
  pkg/prow/plugins/help/help.go
  pkg/prow/plugins/label/label.go
  pkg/prow/plugins/lgtm/lgtm.go
  pkg/prow/plugins/lifecycle/close.go
  pkg/prow/plugins/lifecycle/close_test.go
  pkg/prow/plugins/lifecycle/reopen.go
  pkg/prow/plugins/lifecycle/reopen_test.go
  pkg/prow/plugins/milestone/milestone.go
  pkg/prow/plugins/milestonestatus/milestonestatus.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
  pkg/prow/plugins/pony/pony.go
  pkg/prow/plugins/shrug/shrug.go
  pkg/prow/plugins/sigmention/sigmention.go
  pkg/prow/plugins/skip/skip.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/pull-request.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/welcome/welcome.go
  pkg/prow/plugins/welcome/welcome_test.go
  pkg/prow/plugins/yuks/yuks.go
  pkg/webhook/webhook.go
Labels: approved, size/L

#63 chore: upgrade to latest go-scm
  go.mod
  go.sum
Labels: approved, size/XS
