Repository jenkins-x/lighthouse, pull requests merged in 2019-12, with the labels that each got.

#392 fix: allow the docker registry to be passed in if its defined
  pkg/plumber/plumber.go
  pkg/prow/plugins/trigger/pull-request.go
Labels: approved, size/XS

#400 fix: Switch to new bot test user
  bdd/github/ci.sh
  bdd/github/parameters.yaml
  jenkins-x-github.yml
Labels: approved, lgtm, size/XS

#402 fix: tone down error logging
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/S
