Repository jenkins-x/lighthouse, pull requests merged in 2019-11, with the labels that each got.

#312 fix: first spike at adding support for GitHub App tokens
  charts/lighthouse/templates/tide-deployment.yaml
  charts/lighthouse/templates/tide-githubapp-secrets.yaml
  charts/lighthouse/values.yaml
  cmd/tide/main.go
  pkg/tide/githubapp/factory.go
  pkg/tide/githubapp/github_app_ctrl.go
  pkg/tide/githubapp/owner_query.go
  pkg/tide/githubapp/owner_query_test.go
  pkg/tide/githubapp/owner_tokens_dir.go
  pkg/tide/githubapp/owner_tokens_dir_test.go
  pkg/tide/githubapp/test_data/config.yaml
  pkg/tide/githubapp/test_data/secret_dir/github-app-github-github-aps-shoulderthunder-0
  pkg/tide/githubapp/test_data/secret_dir/username
  pkg/tide/history/history.go
  pkg/tide/interface.go
  pkg/tide/tide.go
  pkg/tide/tide_test.go
Labels: approved, lgtm, size/XL

#316 fix: possible nil pointer core dump
  pkg/prow/plugins/approve/approvers/owners.go
Labels: approved, size/XS

#324 fix: properly base64 encode the github app user name
  charts/lighthouse/templates/tide-githubapp-secrets.yaml
  charts/lighthouse/values.yaml
Labels: approved, size/XS

#334 fix: avoid unnecessary secret mounting if using github apps mode
  charts/lighthouse/templates/tide-deployment.yaml
Labels: approved, size/XS

#337 feat(tests): add BDD tests
  bdd/default/README.md
  bdd/default/ci.sh
  bdd/default/cluster.yaml
  bdd/default/jx-requirements.yml
  bdd/default/parameters.yaml
  bdd/default/values.yaml.template
  jenkins-x.yml
Labels: approved, lgtm, size/L

#353 feat(tests): first spike of webhook unit tests
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/M

#356 fix: lets default to the current bot user being trusted
  go.sum
  pkg/prow/plugins/trigger/trigger.go
Labels: approved, lgtm, size/XS

#361 fix(tests): use faked k8s client in webhook tests
  pkg/webhook/test_data/test_config.yaml
  pkg/webhook/test_data/test_plugins.yaml
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/XXL

#369 chore: Update ci.shs for BDD tests to continue to work right
  bdd/ghe/ci.sh
  bdd/github/ci.sh
Labels: approved, lgtm, size/S
