Repository jenkins-x/lighthouse, pull requests merged in 2020-07, with the labels that each got.

#845 Fixing some 404s
  README.md
Labels: approved, lgtm, size/XS

#848 fix: Use $() instead of ${} in pipeline params
  go.sum
  jenkins-x-bbs.yml
  jenkins-x-ghe.yml
  jenkins-x-github.yml
  jenkins-x-gitlab.yml
  jenkins-x.yml
Labels: size/M, updatebot

#868 chore: Remove lighthouse-jx-controller from repo
  Makefile
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
  bdd/helm-requirements.yaml.template
  bdd/lh-jx-values.yaml
  charts/lighthouse/templates/_helpers.tpl
  charts/lighthouse/templates/jx-controller-deployment.yaml
  charts/lighthouse/templates/jx-controller-rb.yaml
  charts/lighthouse/templates/jx-controller-role.yaml
  charts/lighthouse/templates/jx-controller-sa.yaml
  charts/lighthouse/values.yaml
  cmd/jxcontroller/main.go
  go.mod
  go.sum
  jenkins-x-bbs.yml
  jenkins-x-ghe.yml
  jenkins-x-github.yml
  jenkins-x-gitlab.yml
  jenkins-x-tekton.yml
  jenkins-x.yml
  pkg/engines/jx/activity.go
  pkg/engines/jx/activity_test.go
  pkg/engines/jx/controller.go
  pkg/engines/jx/controller_test.go
  pkg/engines/jx/helpers.go
  pkg/engines/jx/test_data/controller/no-job-for-activity/observed-activity.yml
  pkg/engines/jx/test_data/controller/start-pullrequest/expected-activity.yml
  pkg/engines/jx/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/jx/test_data/controller/start-pullrequest/observed-lhjob.yml
  pkg/engines/jx/test_data/controller/update-job/expected-lhjob.yml
  pkg/engines/jx/test_data/controller/update-job/observed-activity.yml
  pkg/engines/jx/test_data/controller/update-job/observed-lhjob.yml
  pkg/engines/jx/test_data/lhjob.yaml
  pkg/engines/jx/test_data/pipelineactivity.yaml
  pkg/engines/jx/test_data/record.yaml
Labels: approved, size/XXL, updatebot

#870 fix: Don't make tidy-deps on jx
  jenkins-x.yml
Labels: size/XS, updatebot

#872 fix(tekton): Better PR and stage naming, set owner refs for cleanup
  pkg/apis/lighthouse/register.go
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/engines/tekton/activity.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/test_data/activity/failed_single_task/pr.yaml
  pkg/engines/tekton/test_data/activity/failed_single_task/record.yaml
  pkg/engines/tekton/test_data/activity/running_multiple_tasks/pr.yaml
  pkg/engines/tekton/test_data/activity/running_multiple_tasks/record.yaml
  pkg/engines/tekton/test_data/activity/running_single_task/pr.yaml
  pkg/engines/tekton/test_data/activity/running_single_task/record.yaml
  pkg/engines/tekton/test_data/activity/successful_multiple_tasks/pr.yaml
  pkg/engines/tekton/test_data/activity/successful_multiple_tasks/record.yaml
  pkg/engines/tekton/test_data/activity/successful_single_task/pr.yaml
  pkg/engines/tekton/test_data/activity/successful_single_task/record.yaml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/update-job/expected-lhjob.yml
Labels: size/M, updatebot

#873 chore: Move various env-var-related functions to util
  cmd/keeper/main.go
  pkg/foghorn/controller.go
  pkg/util/scmclient.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/L, updatebot

#876 feat: Add back the Prow-style config updater plugin
  charts/lighthouse/templates/foghorn-role.yaml
  charts/lighthouse/templates/keeper-role.yaml
  charts/lighthouse/templates/webhooks-role.yaml
  cmd/foghorn/main.go
  cmd/keeper/main.go
  cmd/tektoncontroller/main.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/engines/tekton/controller.go
  pkg/foghorn/controller.go
  pkg/plugins/config.go
  pkg/plugins/config_test.go
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/updateconfig/updateconfig_test.go
  pkg/util/scmclient.go
  pkg/util/stopper.go
  pkg/watcher/configmap_watcher.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/XXL, updatebot
