Repository jenkins-x/lighthouse, pull requests merged in 2020-11, with the labels that each got.

#1141 fix: add better default value
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs-sub-dir/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-append-steps/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-prepend-steps/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-without-params/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml
Labels: approved, lgtm, size/L

#1140 docs: Fix Lighthouse lgtm link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#1144 fix: fix for OpenShift 4.x
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-push/expected-pr.yml
Labels: approved, lgtm, size/S

#1146 feat: handle custom trigger commands for a deployment
  charts/lighthouse/README.md
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
  pkg/plugins/trigger/trigger.go
Labels: approved, lgtm, size/M

#1148 fix: support opting out of default lighthouse parameter defaulting
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-disable-params/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task-disable-params/source.yaml
Labels: approved, lgtm, size/L

#1147 fix: add retry handler to updating lighthousejobs
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/test_data/controller/update-job/observed-lhjob.yml
Labels: approved, lgtm, size/M

#1149 chore: lets only create the jenkins controller secret when the jenkins engine is enabled like the other jenkins specific k8s resources
  charts/lighthouse/templates/jenkins-controller-secret.yaml
Labels: approved, lgtm, size/XS

#1166 fix(chart): foghorn is missing the HMAC token
  charts/lighthouse/templates/foghorn-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS
