Repository jenkins-x/lighthouse, pull requests merged in 2020-06, with the labels that each got.

#772 fix: Handle GitHub and BitBucket Server review approvals same as /approve
  go.sum
  pkg/webhook/events.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/M, updatebot

#777 fix: Support requiring for contexts with conditional execution
  pkg/config/keeper.go
  pkg/config/keeper_test.go
Labels: size/L, updatebot

#778 fix: missing ServiceAccount for gc-jobs
  charts/lighthouse/templates/gc-jobs-sa.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#780 fix: Correct path for gc-jobs command in cronjob
  charts/lighthouse/templates/gc-jobs-cj.yaml
  charts/lighthouse/values.yaml
Labels: size/XS, updatebot

#790 fix: Stop sending version info for root URL
  pkg/webhook/webhook.go
Labels: size/S, updatebot

#791 fix: OWNERS link in approval notifier comment fix, and a bunch of little BitBucket Server formatting fixes
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/approve/approvers/approvers_test.go
  pkg/plugins/approve/approvers/owners.go
  pkg/plugins/assign/assign.go
  pkg/plugins/assign/assign_test.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved_test.go
  pkg/plugins/dog/dog.go
  pkg/plugins/help/help.go
  pkg/plugins/label/label.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lifecycle/close.go
  pkg/plugins/lifecycle/close_test.go
  pkg/plugins/lifecycle/reopen.go
  pkg/plugins/lifecycle/reopen_test.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/pony/pony.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/skip/skip.go
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/yuks/yuks.go
  pkg/scmprovider/client.go
  pkg/scmprovider/fake/fake.go
  pkg/scmprovider/reporter/reporter.go
Labels: size/L, updatebot

#802 fix: Don't error out completely if .gitattributes doesn't exist
  pkg/plugins/size/size.go
Labels: approved, lgtm, size/XS

#805 chore: Add external plugin support like Prow
  pkg/util/constants.go
  pkg/util/externalplugins.go
  pkg/webhook/events.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/L, updatebot

#813 feat: Work towards supporting other engines besides jx
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/foghorn/controller.go
  pkg/jx/activity.go
  pkg/jx/activity_test.go
  pkg/jx/helpers.go
  pkg/jx/launcher.go
  pkg/jx/test_data/lhjob.yaml
  pkg/jx/test_data/pipelineactivity.yaml
  pkg/jx/test_data/record.yaml
  pkg/keeper/githubapp/factory.go
  pkg/keeper/githubapp/github_app_ctrl.go
  pkg/keeper/keeper.go
  pkg/launcher/fake/fake.go
  pkg/launcher/interface.go
  pkg/plugins/override/override.go
  pkg/plugins/plugins.go
  pkg/plugins/trigger/push.go
  pkg/plugins/trigger/trigger.go
  pkg/record/record.go
  pkg/util/constants.go
  pkg/util/externalplugins.go
  pkg/webhook/events.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/XXL, updatebot

#817 fix: Stop using github.com/jenkins-x/jx/v2/pkg/log since it's going away
  pkg/scmprovider/issues.go
Labels: size/XS, updatebot

#821 fix: Bump to k8s 1.16.5 dependencies
  Makefile
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/lighthouse/v1alpha1/fake/fake_lighthousejob.go
  pkg/client/clientset/versioned/typed/lighthouse/v1alpha1/lighthouse_client.go
  pkg/client/clientset/versioned/typed/lighthouse/v1alpha1/lighthousejob.go
  pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/keeper/pipelinerun_monitor_test.go
  pkg/metrics/metrics.go
  pkg/watcher/configmap_watcher.go
Labels: size/XXL, updatebot

#833 fix: Lower-case owner/org in Foghorn job lookup
  pkg/foghorn/controller.go
Labels: size/XS, updatebot

#826 chore: Pull plugin config types from lighthouse-config
  go.mod
  go.sum
  pkg/labels/labels.go
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/blockade/blockade_test.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved_test.go
  pkg/plugins/config.go
  pkg/plugins/config_test.go
  pkg/plugins/help/help.go
  pkg/plugins/help/help_test.go
  pkg/plugins/hold/hold.go
  pkg/plugins/hold/hold_test.go
  pkg/plugins/label/label_test.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/lifecycle/lifecycle_test.go
  pkg/plugins/owners-label/owners-label_test.go
  pkg/plugins/plugins.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/shrug/shurg_test.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/sigmention/sigmention_test.go
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/plugins/trigger/pull-request.go
  pkg/plugins/trigger/pull-request_test.go
  pkg/plugins/types.go
  pkg/plugins/wip/wip-label.go
  pkg/plugins/wip/wip-label_test.go
  pkg/scmprovider/test_helpers.go
Labels: size/XXL, updatebot

#836 chore: Switch to using jx-api
  Makefile
  cmd/foghorn/main.go
  go.mod
  go.sum
  pkg/clients/clients.go
  pkg/foghorn/controller.go
  pkg/jx/activity.go
  pkg/jx/activity_test.go
  pkg/jx/helpers.go
  pkg/jx/launcher.go
  pkg/logrusutil/logrusutil.go
Labels: size/M, updatebot
