Repository jenkins-x/lighthouse, pull requests merged in 2020-10, with the labels that each got.

#1092 chore: Set the default replica count for webhooks to 1
  charts/lighthouse/README.md
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#1088 fix: Ensure status URL gets updated in LighthouseJob
  pkg/engines/jenkins/controller.go
  pkg/engines/jenkins/jenkins.go
Labels: approved, lgtm, size/S

#1090 chore: Remove obsolete dependency-matrix directory
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
Labels: approved, lgtm, size/S

#1100 docs: explain how to swap deployments using telepresence
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#1104 fix: possible concurrent modification errors using in repo config
  pkg/triggerconfig/merge/merge.go
Labels: approved, lgtm, size/S

#1109 fix: Fix flaky calculate_test
  pkg/triggerconfig/inrepo/calculate_test.go
Labels: approved, size/S, updatebot

#1111 fix: typo
  docs/install_lighthouse_with_jenkins.md
Labels: approved, lgtm, ok-to-test, size/XS

#1114 fix: handle case when master or new PR don't have jx config
  pkg/triggerconfig/inrepo/calculate.go
Labels: approved, lgtm, ok-to-test, size/XS

#1121 fix: bug in merge logic
  pkg/triggerconfig/merge/merge.go
Labels: approved, lgtm, size/S

#1120 fix: improve the validation of presubmit jobs
  pkg/config/config_test.go
  pkg/config/job/config.go
Labels: approved, lgtm, size/XS

#1127 fix: improve tekton catalog integration
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/load_triggers.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/demo-deploy-kubectl.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/git-clone.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/kaniko.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-load-refs/unit-tests.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/demo-deploy-kubectl.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/git-clone.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/kaniko.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline/unit-tests.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/add-params.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/pipeline-with-extra-params.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr-load-refs/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pr/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/taskrun/source.yaml
Labels: approved, lgtm, size/XXL

#1125 feat: Make inrepo config merge current PR branch config
  pkg/scmprovider/legacy_helpers.go
  pkg/webhook/events.go
Labels: approved, lgtm, ok-to-test, size/M

#1129 fix: Make inrepo triggers config filename consistent
  pkg/triggerconfig/inrepo/load_triggers.go
Labels: approved, lgtm, ok-to-test, size/XS

#1131 fix: log failure raison since not possible to sent to gitlab
  pkg/keeper/status.go
  pkg/keeper/status_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#1133 fix: added trigger docs
  Makefile
  docs/trigger/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/trigger/github-com-jenkins-x-lighthouse-pkg-triggerconfig.md
  docs/trigger/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/trigger/github-com-tektoncd-pipeline-pkg-apis-resource-v1alpha1.md
  docs/trigger/k8s-io-api-core-v1.md
  docs/trigger/k8s-io-apimachinery-pkg-api-resource.md
  docs/trigger/k8s-io-apimachinery-pkg-apis-meta-v1.md
  docs/trigger/k8s-io-apimachinery-pkg-types.md
  docs/trigger/k8s-io-apimachinery-pkg-util-intstr.md
Labels: approved, lgtm, size/XXL

#1132 fix: use assign PR in plugins when working with PR instead of assign issue
  pkg/plugins/assign/assign.go
  pkg/plugins/assign/assign_test.go
  pkg/plugins/lgtm/lgtm.go
  pkg/scmprovider/pull_requests.go
Labels: approved, lgtm, ok-to-test, size/M
