Repository jenkins-x/lighthouse, pull requests merged in 2020-03, with the labels that each got.

#560 fix: Override shouldn't create new builds
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/override/override_test.go
Labels: approved, size/M, updatebot

#550 fix: Simple state for running pipeline should be pending, not failure
  pkg/tide/tide.go
Labels: size/XS, updatebot

#573 feat: add a pipeline for whitesource dependencies scanning
  .whitesource.config
  jenkins-x-whitesource.yml
Labels: approved, lgtm, size/L

#575 chore: Remove pointless/confusing log message
  pkg/tide/tide.go
Labels: size/S, updatebot

#578 fix: overridden status takes precedence over latest build result
  bdd/github/ci.sh
  bdd/github/jx-requirements.yml
  jenkins-x-github.yml
  jenkins-x.yml
  pkg/plumber/plumber.go
  pkg/plumber/test_data/convert/batch/expected.yaml
  pkg/plumber/test_data/convert/presubmit/expected.yaml
  pkg/plumber/types.go
  pkg/prow/plugins/override/override.go
  pkg/tide/tide.go
  pkg/tide/tide_test.go
  pkg/util/constants.go
Labels: size/L, updatebot

#583 fix: Use x-access-token as username in git client with GHA
  pkg/tide/githubapp/github_app_ctrl.go
  pkg/util/constants.go
Labels: approved, size/S, updatebot

#582 chore: Stop using github and prow in type/interface/field/variable names
  pkg/prow/commentpruner/commentpruner.go
  pkg/prow/commentpruner/commentpruner_test.go
  pkg/prow/config/jobs.go
  pkg/prow/plugins/approve/approve.go
  pkg/prow/plugins/approve/approve_test.go
  pkg/prow/plugins/assign/assign.go
  pkg/prow/plugins/blockade/blockade.go
  pkg/prow/plugins/blockade/blockade_test.go
  pkg/prow/plugins/branchcleaner/branchcleaner.go
  pkg/prow/plugins/cat/cat.go
  pkg/prow/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/prow/plugins/dog/dog.go
  pkg/prow/plugins/help/help.go
  pkg/prow/plugins/help/help_test.go
  pkg/prow/plugins/hold/hold.go
  pkg/prow/plugins/label/label.go
  pkg/prow/plugins/lgtm/lgtm.go
  pkg/prow/plugins/lgtm/lgtm_test.go
  pkg/prow/plugins/lifecycle/lifecycle.go
  pkg/prow/plugins/lifecycle/reopen.go
  pkg/prow/plugins/milestone/milestone.go
  pkg/prow/plugins/milestonestatus/milestonestatus.go
  pkg/prow/plugins/override/override.go
  pkg/prow/plugins/owners-label/owners-label.go
  pkg/prow/plugins/owners-label/owners-label_test.go
  pkg/prow/plugins/plugins.go
  pkg/prow/plugins/pony/pony.go
  pkg/prow/plugins/shrug/shrug.go
  pkg/prow/plugins/sigmention/sigmention.go
  pkg/prow/plugins/size/size.go
  pkg/prow/plugins/size/size_test.go
  pkg/prow/plugins/skip/skip.go
  pkg/prow/plugins/skip/skip_test.go
  pkg/prow/plugins/stage/stage.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/plugins/trigger/pull-request.go
  pkg/prow/plugins/trigger/pull-request_test.go
  pkg/prow/plugins/trigger/push_test.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/trigger/trigger_test.go
  pkg/prow/plugins/welcome/welcome.go
  pkg/prow/plugins/welcome/welcome_test.go
  pkg/prow/plugins/wip/wip-label.go
  pkg/prow/plugins/yuks/yuks.go
  pkg/prow/repoowners/repoowners.go
  pkg/prow/repoowners/repoowners_test.go
  pkg/tide/blockers/blockers.go
  pkg/tide/status.go
  pkg/tide/status_test.go
  pkg/tide/tide.go
  pkg/tide/tide_test.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: size/XXL, updatebot

#590 fix: Add support for GitHub App authentication to webhook controller
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/tide-deployment.yaml
  charts/lighthouse/templates/tide-githubapp-secrets.yaml
  charts/lighthouse/values.yaml
  cmd/tide/main.go
  pkg/tide/githubapp/factory.go
  pkg/tide/githubapp/github_app_ctrl.go
  pkg/util/constants.go
  pkg/util/files.go
  pkg/util/githubapp.go
  pkg/util/owner_tokens_dir.go
  pkg/util/owner_tokens_dir_test.go
  pkg/util/scmclient.go
  pkg/util/test_data/secret_dir/github-app-github-github-aps-shoulderthunder-0
  pkg/util/test_data/secret_dir/username
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/L

#601 fix: allow the default jx image to be configured via helm
  bdd/values.yaml.template
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/values.yaml
  pkg/plumber/plumber.go
Labels: approved, lgtm, size/XS

#613 fix: Return 500 for unknown repositories when in GitHub App mode
  pkg/webhook/test_data/test_config.yaml
  pkg/webhook/test_data/test_plugins.yaml
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/XXL

#615 chore: Remove app lifecycle tests
  bdd/ghe/ci.sh
  bdd/github/ci.sh
Labels: size/XS, updatebot

#619 chore: allow log format to be configured
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#620 fix: Don't recreate the metapipeline client for each GHA tide sync
  pkg/tide/githubapp/factory.go
  pkg/tide/githubapp/github_app_ctrl.go
Labels: approved, lgtm, size/S

#621 fix: Switch to using NewIndexInformerWatcher for webhook config
  pkg/watcher/configmap_watcher.go
Labels: approved, lgtm, size/S
