Repository jenkins-x/lighthouse, pull requests merged in 2020-08, with the labels that each got.

#877 fix: Forgot to import config-updater into binaries
  pkg/foghorn/plugins.go
  pkg/webhook/plugins.go
Labels: updatebot

#878 fix: Need to pass kube client to plugin agent
  pkg/plugins/plugins.go
Labels: size/XS, updatebot

#879 fix: Get rid of whitelist/blacklist terminology
  pkg/config/config.go
  pkg/config/jobs.go
  pkg/keeper/status.go
  pkg/keeper/status_test.go
  pkg/plugins/config.go
  pkg/repoowners/repoowners.go
  pkg/repoowners/repoowners_test.go
  pkg/webhook/test_data/test_config.yaml
  test/e2e/test_data/example-config.tmpl.yml
Labels: size/L, updatebot

#881 feat(tekton): Set a default 24 hour timeout for created PipelineRuns
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
Labels: size/XS, updatebot

#883 feat: Comment on PRs that failed to merge
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
Labels: approved, lgtm, size/L

#888 fix: Only use GraphQL for GitHub
  go.mod
  go.sum
  pkg/scmprovider/client.go
Labels: size/XS, updatebot

#890 feat(tekton): Support git-batch-merge Task parameters
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-pipeline.yml
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/trigger/trigger.go
  pkg/scmprovider/client.go
  pkg/scmprovider/fake/fake.go
  test/e2e/tekton_test.go
  test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
Labels: size/L, updatebot

#892 fix: Check if OwnersDirExcludes is non-nil before using it
  pkg/repoowners/repoowners.go
Labels: size/S, updatebot

#894 fix: Set git-batch-merge depth parameter in test
  bdd/tekton/ci.sh
  test/e2e/tekton_test.go
  test/e2e/test_data/passingRepoScript.sh
  test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
Labels: size/S, updatebot

#896 feat: Add non-jx install docs
  README.md
  bdd/bbs/ci.sh
  bdd/capture-failed-pod-logs.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
  bdd/tekton/ci.sh
  charts/lighthouse/templates/config-cm.yaml
  charts/lighthouse/templates/plugins-cm.yaml
  charts/lighthouse/values.yaml
  docs/INSTALL.md
  test/e2e/tekton_test.go
  test/e2e/test_data/tekton/pipelineAndTask.tmpl.yaml
Labels: size/L, updatebot

#897 fix: add a new repoconfig package and file format
  pkg/apis/lighthouse/v1alpha1/repoconfig_config_types.go
  pkg/apis/lighthouse/v1alpha1/repoconfig_plugins_types.go
  pkg/apis/lighthouse/v1alpha1/repoconfig_types.go
  pkg/repoconfig/merge/combine.go
  pkg/repoconfig/merge/combine_test.go
  pkg/repoconfig/merge/converters.go
  pkg/repoconfig/merge/helpers.go
  pkg/repoconfig/merge/merge.go
  pkg/repoconfig/merge/merge_test.go
  pkg/repoconfig/merge/test_data/simple/expected-config.yaml
  pkg/repoconfig/merge/test_data/simple/expected-plugins.yaml
  pkg/repoconfig/merge/test_data/simple/lighthouse.yaml
  pkg/repoconfig/merge/test_data/simple/source-config.yaml
  pkg/repoconfig/merge/test_data/simple/source-plugins.yaml
  pkg/repoconfig/scmload/load.go
  pkg/repoconfig/scmload/load_integration_test.go
  pkg/repoconfig/scmload/load_test.go
  pkg/repoconfig/scmload/test_data/myorg/myrepo/.lighthouse/dummy/README.md
  pkg/repoconfig/scmload/test_data/myorg/myrepo/.lighthouse/jenkins-x/lighthouse.yaml
  pkg/repoconfig/scmload/test_data/myorg/myrepo/.lighthouse/linter/lighthouse.yaml
Labels: approved, lgtm, size/XXL

#898 chore: Add a few more plugins to the default setup
  charts/lighthouse/templates/plugins-cm.yaml
  test/e2e/test_data/example-plugins.tmpl.yml
Labels: size/S, updatebot

#901 fix: Fix helm chart missing argument in ne condition
  charts/lighthouse/templates/plugins-cm.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#903 feat: Validate config-updater changes before merging
  README.md
  pkg/apis/lighthouse/v1alpha1/repoconfig_config_types.go
  pkg/plugins/updateconfig/test_data/invalid-config.yaml
  pkg/plugins/updateconfig/test_data/invalid-yaml.yaml
  pkg/plugins/updateconfig/test_data/valid-config.yaml
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/updateconfig/updateconfig_test.go
Labels: size/XXL, updatebot

#904 fix: Use the HEAD SHA for config updater check, since merge SHA may be empty
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/updateconfig/updateconfig_test.go
Labels: size/S, updatebot

#905 feat: Make config-updater file name in comment a link
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approvers/owners.go
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/updateconfig/updateconfig_test.go
  pkg/util/scmclient.go
Labels: size/M, updatebot

#911 fix: removing obsolete github.com/jtnord/logrus replace in go.mod
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#908 chore: Add makefile and (potentially) OWNERS to helmignore
  charts/lighthouse/.helmignore
Labels: approved, lgtm, ok-to-test, size/XS

#909 chore: Improve chart notes
  charts/lighthouse/templates/NOTES.txt
Labels: approved, lgtm, ok-to-test, size/S

#907 feat: Support passing config.yaml and plugins.yaml to helm chart
  charts/lighthouse/templates/config-cm.yaml
  charts/lighthouse/templates/plugins-cm.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#915 chore: Add check of fmt and other targets not having modified code
  Makefile
  jenkins-x.yml
Labels: size/M, updatebot

#916 fix: Stop using in-cluster chartmuseum in BDD requirements
  bdd/helm-requirements.yaml.template
Labels: size/XS, updatebot

#914 feat: Add helm docs
  charts/lighthouse/.helmignore
  charts/lighthouse/Chart.yaml
  charts/lighthouse/Makefile
  charts/lighthouse/README.md
  charts/lighthouse/README.md.gotmpl
Labels: approved, lgtm, ok-to-test, size/L

#917 docs: Initiate plugins documentation
  docs/PLUGINS.md
Labels: approved, lgtm, ok-to-test, size/M

#918 chore: Remove golint and blunderbuss plugins config (dead code)
  charts/lighthouse/templates/plugins-cm.yaml
  pkg/plugins/config.go
  pkg/repoconfig/merge/test_data/simple/expected-plugins.yaml
  pkg/repoconfig/merge/test_data/simple/source-plugins.yaml
  pkg/webhook/test_data/test_plugins.yaml
  test/e2e/test_data/example-plugins.tmpl.yml
Labels: approved, lgtm, ok-to-test, size/M

#919 docs: Add yuks plugin docs
  docs/PLUGINS.md
  docs/plugins/yuks.md
Labels: approved, lgtm, size/M

#920 docs: Add wip plugin docs
  docs/PLUGINS.md
  docs/plugins/wip.md
Labels: approved, lgtm, size/M

#922 docs: Add shrug plugin docs
  docs/PLUGINS.md
  docs/plugins/shrug.md
Labels: approved, lgtm, size/M

#923 docs: Add lh-joke command to yuks plugin docs
  docs/plugins/yuks.md
Labels: approved, lgtm, size/XS

#924 docs: Add size plugin docs
  docs/PLUGINS.md
  docs/plugins/size.md
Labels: approved, lgtm, size/M

#921 docs: Add welcome plugin docs
  docs/PLUGINS.md
  docs/plugins/welcome.md
Labels: approved, lgtm, size/M

#925 chore: Remove slack plugin config (dead code)
  charts/lighthouse/templates/plugins-cm.yaml
  docs/PLUGINS.md
  pkg/plugins/config.go
  pkg/repoconfig/merge/test_data/simple/expected-plugins.yaml
  pkg/repoconfig/merge/test_data/simple/source-plugins.yaml
  pkg/webhook/test_data/test_plugins.yaml
  test/e2e/test_data/example-plugins.tmpl.yml
Labels: approved, lgtm, size/M

#913 chore: Add REPO_URL and PULL_PULL_REF Tekton parameters
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/apis/lighthouse/v1alpha1/types_test.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
Labels: approved, lgtm, size/M

#929 fix: allow to run binaries locally
  go.mod
  go.sum
  pkg/clients/clients.go
  pkg/util/go_mod_tidy_hack.go
Labels: approved, lgtm, size/XL

#932 docs: Add hold plugin docs
  docs/PLUGINS.md
  docs/plugins/hold.md
Labels: approved, lgtm, size/M

#931 fix: Check for nil of config, not getter
  pkg/util/scmclient.go
Labels: approved, lgtm, size/S

#927 feat: Add pipeline_run_params support to lighthouse job
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/apis/lighthouse/v1alpha1/zz_generated.deepcopy.go
  pkg/config/jobs.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
  test/e2e/tekton_test.go
Labels: approved, lgtm, size/L

#935 fix: adding nil check for pluginConfig.Config() in util.ExternalPluginsForEvent
  pkg/util/externalplugins.go
  pkg/util/externalplugins_test.go
Labels: approved, lgtm, size/S

#937 fix: remove dependency to TV4/logrus-stackdriver-formatter
  go.mod
  go.sum
  pkg/logrusutil/logrusutil.go
  pkg/logrusutil/logrusutil_test.go
  pkg/logrusutil/stackdriver/formatter.go
  pkg/logrusutil/stackdriver/formatter_test.go
Labels: approved, lgtm, size/XXL

#938 feat: migrate tektoncontroller to controller-runtime
  cmd/tektoncontroller/main.go
  go.mod
  go.sum
  pkg/engines/tekton/constants.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/update-job/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/update-job/observed-lhjob.yml
  pkg/engines/tekton/utils.go
Labels: approved, lgtm, size/XXL

#940 fix: Wrap payload passed to pipeline_run_params
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/observed-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
  pkg/engines/tekton/utils.go
  test/e2e/tekton_test.go
Labels: approved, lgtm, size/M

#942 chore: remove obsolete tektonclient in tektoncontroller
  pkg/engines/tekton/controller.go
Labels: approved, lgtm, size/XS

#944 fix: Speed up codegen considerably
  hack/generate-groups.sh
Labels: approved, lgtm, size/S

#943 chore: Switch foghorn controller to use controller-runtime
  cmd/foghorn/main.go
  cmd/tektoncontroller/main.go
  go.mod
  go.sum
  pkg/foghorn/controller.go
  pkg/foghorn/controller_test.go
  pkg/foghorn/test_data/no-status-change/expected-lhjob.yml
  pkg/foghorn/test_data/no-status-change/observed-lhjob.yml
  pkg/foghorn/test_data/status-change/expected-lhjob.yml
  pkg/foghorn/test_data/status-change/observed-lhjob.yml
Labels: approved, lgtm, size/XL

#947 refactor: Get rid of cobra stuff in webhooks
  Dockerfile.webhooks
  Makefile
  cmd/webhooks/main.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, lgtm, size/L

#946 feat: generate CRDs from types
  Makefile
  crds/lighthouse.jenkins.io_lighthousejobs.yaml
  pkg/apis/lighthouse/v1alpha1/types.go
Labels: approved, lgtm, size/XXL

#961 chore: remove deck and sinker config (deadcode)
  charts/lighthouse/templates/config-cm.yaml
  config.yaml
  docs/config/Lighthouse config.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/foghorn/controller_test.go
  pkg/repoconfig/merge/test_data/simple/expected-config.yaml
  pkg/repoconfig/merge/test_data/simple/source-config.yaml
  pkg/webhook/test_data/test_config.yaml
  test/e2e/test_data/example-config.tmpl.yml
Labels: approved, lgtm, size/L

#962 chore: remove most of Plank config
  docs/config/Lighthouse config.md
  pkg/config/config.go
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
Labels: approved, lgtm, size/L

#964 chore: replace clients.GetConfig with clientcmd.BuildConfigFromFlags
  cmd/foghorn/main.go
  cmd/gc/main.go
  cmd/tektoncontroller/main.go
  pkg/clients/clients.go
Labels: approved, lgtm, size/M

#966 chore: remove Gerrit config
  charts/lighthouse/templates/config-cm.yaml
  config.yaml
  docs/config/Lighthouse config.md
  pkg/config/config.go
  pkg/foghorn/controller_test.go
  pkg/repoconfig/merge/test_data/simple/expected-config.yaml
  pkg/repoconfig/merge/test_data/simple/source-config.yaml
  pkg/webhook/test_data/test_config.yaml
  test/e2e/test_data/example-config.tmpl.yml
Labels: approved, lgtm, size/M

#968 refactor: rework jobs config
  Makefile
  cmd/keeper/main.go
  docs/config/Lighthouse config.md
  docs/crds/Lighthouse (v1alpha1).md
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/apis/lighthouse/v1alpha1/zz_generated.deepcopy.go
  pkg/config/branch_protection.go
  pkg/config/branch_protection_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/constants.go
  pkg/config/job/base.go
  pkg/config/job/brancher.go
  pkg/config/job/changedfilesprovider.go
  pkg/config/job/config.go
  pkg/config/job/constants.go
  pkg/config/job/jobs.go
  pkg/config/job/periodic.go
  pkg/config/job/pipelinerunparam.go
  pkg/config/job/postsubmit.go
  pkg/config/job/preset.go
  pkg/config/job/presubmit.go
  pkg/config/job/regexpchangematcher.go
  pkg/config/job/reporter.go
  pkg/config/job/utilityconfig.go
  pkg/config/jobs.go
  pkg/config/keeper_test.go
  pkg/config/util/util.go
  pkg/engines/tekton/controller.go
  pkg/foghorn/controller_test.go
  pkg/jobutil/filter.go
  pkg/jobutil/filter_test.go
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/skip/skip.go
  pkg/plugins/skip/skip_test.go
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/plugins/trigger/pull-request.go
  pkg/plugins/trigger/pull-request_test.go
  pkg/plugins/trigger/push.go
  pkg/plugins/trigger/push_test.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/trigger/trigger_test.go
  pkg/repoconfig/merge/converters.go
  pkg/repoconfig/merge/merge.go
  pkg/repoconfig/repoconfig_config_types.go
  test/e2e/tekton_test.go
Labels: approved, lgtm, size/XXL

#979 chore: remove deprecated config elements
  config.yaml
  go.sum
  pkg/config/config_test.go
  pkg/config/job/config.go
  pkg/config/job/periodic.go
  pkg/config/lighthouse/config.go
  pkg/foghorn/controller_test.go
  pkg/repoconfig/merge/test_data/simple/expected-config.yaml
  pkg/repoconfig/merge/test_data/simple/source-config.yaml
Labels: approved, lgtm, size/M

#975 chore: removing obsolete files and directories
  charts/preview/Chart.yaml
  charts/preview/Makefile
  charts/preview/requirements.yaml
  charts/preview/values.yaml
  config.yaml
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  hack/boilerplate/boilerplate.go.txt
  hack/generate-groups.sh
  hack/update-codegen.sh
  skaffold.yaml
  watch.sh
Labels: approved, lgtm, size/L

#977 chore: remove cmd/helper package (deadcode)
  go.mod
  go.sum
  pkg/cmd/helper/error.go
Labels: approved, lgtm, size/L

#981 chore: Improve chart docs
  charts/lighthouse/README.md
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/L

#983 fix: Make keeper image pull policy configuration consistent
  charts/lighthouse/README.md
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#984 chore: add missing chart values for tekton controller
  charts/lighthouse/README.md
  charts/lighthouse/templates/tekton-controller-deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/M

#985 chore: tighten tekton controller rbac permissions
  charts/lighthouse/templates/tekton-controller-role.yaml
  cmd/tektoncontroller/main.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/utils.go
Labels: approved, lgtm, size/M

#988 chore: make webhooks ingress part of webhooks section in chart
  bdd/tekton/values.yaml.template
  charts/lighthouse/README.md
  charts/lighthouse/templates/hook-ingress.yaml
  charts/lighthouse/templates/webhooks-ingress.yaml
  charts/lighthouse/templates/webhooks-service.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/L

#993 docs: Install docs update
  docs/INSTALL.md
Labels: approved, lgtm, size/XL

#994 chore: remove unused files
  Dockerfile.jxcontroller
  custom-boilerplate.go.txt
Labels: approved, lgtm, size/XS

#995 chore: make e2e tests non sensible to the ingress name
  bdd/tekton/values.yaml.template
  charts/lighthouse/README.md
  charts/lighthouse/templates/webhooks-ingress.yaml
  charts/lighthouse/values.yaml
  test/e2e/helpers.go
Labels: approved, lgtm, size/S

#997 chore: Switch Tekton engine build ID to epoch milliseconds
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/utils.go
Labels: approved, lgtm, size/M

#999 refactor: generate better docs
  Makefile
  docs/config/Lighthouse config.md
  docs/config/README.md
  docs/config/jobs/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/config/jobs/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/config/jobs/github-com-tektoncd-pipeline-pkg-apis-resource-v1alpha1.md
  docs/config/jobs/k8s-io-api-core-v1.md
  docs/config/jobs/k8s-io-apimachinery-pkg-api-resource.md
  docs/config/jobs/k8s-io-apimachinery-pkg-apis-meta-v1.md
  docs/config/jobs/k8s-io-apimachinery-pkg-types.md
  docs/config/jobs/k8s-io-apimachinery-pkg-util-intstr.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-branchprotection.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-keeper.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-lighthouse.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-org.md
  docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md
  docs/crds/Lighthouse (v1alpha1).md
  docs/crds/github-com-jenkins-x-lighthouse-pkg-apis-lighthouse-v1alpha1.md
  docs/crds/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/crds/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/crds/github-com-tektoncd-pipeline-pkg-apis-resource-v1alpha1.md
  docs/crds/k8s-io-api-core-v1.md
  docs/crds/k8s-io-apimachinery-pkg-api-resource.md
  docs/crds/k8s-io-apimachinery-pkg-apis-meta-v1.md
  docs/crds/k8s-io-apimachinery-pkg-types.md
  docs/crds/k8s-io-apimachinery-pkg-util-intstr.md
  hack/struct-docs.go
  pkg/config/job/postsubmit.go
Labels: approved, lgtm, size/XXL
