Repository jenkins-x/lighthouse, pull requests merged in 2020-04, with the labels that each got.

#629 fix: Make sure we've synced the informer watcher for the webhook controller
  pkg/watcher/configmap_watcher.go
  pkg/webhook/webhook.go
Labels: size/M, updatebot

#639 chore: removing downstream dependency update to lighthotel
  jenkins-x.yml
  updatebot.sh
Labels: approved, lgtm, size/XS

#645 fix: Backwards-compatibility for image.repository value
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/S, updatebot

#648 chore: set the whitesoruce image to version 20.3.1
  jenkins-x-whitesource.yml
Labels: size/XS

#652 chore: make logging configuration configurable
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#651 chore: Turn on testing of status reporting link
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
  bdd/values.yaml.template
  pkg/foghorn/controller.go
Labels: size/S, updatebot

#658 fix: Keeper needs permissions to create lighthouse jobs
  charts/lighthouse/templates/keeper-role.yaml
Labels: approved, lgtm, size/S

#657 fix: Change default keeper status label and allow overriding
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/values.yaml
  pkg/keeper/keeper.go
  pkg/keeper/status.go
  pkg/keeper/status_test.go
Labels: approved, lgtm, size/S

#663 fix: Merge method for repo should be used
  go.mod
  go.sum
  pkg/git/git.go
  pkg/keeper/keeper.go
  pkg/scmprovider/pull_requests.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/M, updatebot

#676 fix: Check org members, not just collabs, for approve rights
  go.mod
  go.sum
  pkg/repoowners/repoowners.go
  pkg/scmprovider/client.go
  pkg/scmprovider/fake/fake.go
  pkg/scmprovider/organizations.go
  pkg/webhook/webhook.go
Labels: approved, size/M, updatebot

#661 feat: make team name configuable in the report url
  go.mod
  pkg/foghorn/controller.go
Labels: approved, lgtm, size/S

#671 fix: Stop creating a new launcher client for each webhook event
  pkg/webhook/webhook.go
Labels: approved, size/M, updatebot

#679 fix: Get rid of live-check of SCM status for override
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
  pkg/plugins/override/override.go
Labels: size/L, updatebot

#681 feat: make CRD creation optional
  charts/lighthouse/templates/lighthousejobs-crd.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#683 fix: Properly finalize/default/validate config loaded via watcher
  go.mod
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/foghorn/controller.go
Labels: size/L, updatebot

#687 fix: Fix Gosec G601 failure
  cmd/gc/main.go
  go.mod
  go.sum
  pkg/keeper/keeper.go
  pkg/keeper/pipelinerun_monitor.go
  pkg/keeper/status.go
  pkg/repoowners/repoowners.go
  pkg/watcher/configmap_watcher.go
Labels: size/M, updatebot

#696 fix: Get rid of Deck link
  pkg/keeper/status.go
Labels: approved, lgtm, size/XS

#697 fix: add chart home link and better icon
  charts/lighthouse/Chart.yaml
Labels: approved, lgtm, size/XS
