Repository jenkins-x/lighthouse, pull requests merged in 2020-05, with the labels that each got.

#704 fix: Get all pages of results for provider queries
  go.mod
  go.sum
  pkg/scmprovider/issues.go
  pkg/scmprovider/organizations.go
  pkg/scmprovider/pull_requests.go
  pkg/scmprovider/repositories.go
  pkg/scmprovider/reviews.go
Labels: approved, lgtm, size/L

#710 fix: add a label to the GC Job
  charts/lighthouse/templates/gc-jobs-cj.yaml
Labels: approved, lgtm, size/XS

#712 fix: Get /cc and /uncc to work
  pkg/scmprovider/reviews.go
Labels: size/S, updatebot

#721 fix: Copy jx dependencies into temp JX_HOME
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
Labels: approved, lgtm, size/XS

#717 fix: Use Lighthouse-specific HMAC token secret name
  charts/lighthouse/templates/hmacsecret.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  go.mod
  go.sum
Labels: size/S, updatebot

#723 fix: Failed pipeline report comments should use PR API, not issues
  pkg/scmprovider/reporter/reporter.go
  pkg/scmprovider/reporter/reporter_test.go
Labels: updatebot

#724 fix: Switch SCM client panics to ErrNotSupported
  pkg/scmprovider/client.go
  pkg/scmprovider/issues.go
  pkg/scmprovider/pull_requests.go
Labels: size/S, updatebot

#732 fix: Implement /close
  pkg/scmprovider/issues.go
  pkg/scmprovider/pull_requests.go
Labels: size/S, updatebot

#733 fix: Implement /reopen properly
  go.mod
  go.sum
  pkg/scmprovider/issues.go
  pkg/scmprovider/pull_requests.go
Labels: size/S, updatebot

#734 fix: avoid possible nil pointer
  pkg/plugins/override/override.go
Labels: approved, lgtm, size/XS

#728 feat: BitBucket Server support via comments emulating labels
  bdd/bbs/ci.sh
  pkg/plugins/approve/approve_test.go
  pkg/plugins/lgtm/lgtm_test.go
  pkg/plugins/wip/wip-label_test.go
  pkg/scmprovider/client.go
  pkg/scmprovider/issues.go
  pkg/scmprovider/labels.go
  pkg/scmprovider/pull_requests.go
  pkg/scmprovider/test_helpers.go
Labels: size/XL, updatebot

#747 feat: BitBucket Server support (preview)
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
  cmd/keeper/main.go
  go.mod
  go.sum
  jenkins-x-bbs.yml
  pkg/jobutil/jobutil.go
  pkg/keeper/status.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/size/size.go
  pkg/scmprovider/client.go
  pkg/scmprovider/labels.go
  pkg/scmprovider/organizations.go
  pkg/scmprovider/reporter/reporter.go
Labels: size/M, updatebot

#749 test: Switch back to standard bdd-jx
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
Labels: size/XS, updatebot

#751 chore: Switch jx dependency to semver v2
  cmd/foghorn/main.go
  cmd/gc/main.go
  go.mod
  go.sum
  pkg/apis/lighthouse/v1alpha1/types.go
  pkg/clients/clients.go
  pkg/foghorn/controller.go
  pkg/keeper/githubapp/factory.go
  pkg/keeper/githubapp/github_app_ctrl.go
  pkg/keeper/keeper.go
  pkg/launcher/fake/fake.go
  pkg/launcher/helpers.go
  pkg/launcher/interface.go
  pkg/launcher/launcher.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/plugins.go
  pkg/plugins/trigger/trigger.go
  pkg/scmprovider/issues.go
  pkg/util/owner_tokens_dir.go
  pkg/webhook/events.go
  pkg/webhook/webhook.go
Labels: size/L, updatebot

#761 chore: allow stackdriver formatter
  go.mod
  go.sum
  pkg/logrusutil/logrusutil.go
Labels: approved, lgtm, size/S

#762 chore: configure logrus properties
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
Labels: approved, lgtm, size/XS

#763 chore: remove use of jx step credential
  jenkins-x.yml
Labels: approved, lgtm, size/M

#768 chore: Bump to jx 2.1.55 and update CombineErrors accordingly
  go.mod
  go.sum
  pkg/keeper/githubapp/github_app_ctrl.go
Labels: size/L, updatebot

#775 fix: Increase Keeper memory and CPU limits
  charts/lighthouse/values.yaml
Labels: size/XS, updatebot

#774 chore: add extra logging when determining if builds should trigger
  pkg/plugins/trigger/pull-request.go
  pkg/plugins/trigger/trigger.go
Labels: approved, lgtm, size/XS
