Repository jenkins-x/lighthouse, pull requests merged in 2020-12, with the labels that each got.

#1170 chore(doc): update readme
  README.md
Labels: needs-ok-to-test, size/XS

#1176 fix: file browser couldn't read serverUrl
  pkg/triggerconfig/inrepo/calculate.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, ok-to-test, size/S

#1174 fix: race condition that call reChanges with nil regex
  pkg/config/job/regexpchangematcher.go
Labels: approved, lgtm, ok-to-test, size/S

#1178 fix: Typo fixed '7Path' to 'Path' in cli args help
  cmd/webhooks/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#1186 fix: Deal with Helm stable chart URL change
  bdd/bbs/ci.sh
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
  init-helm.sh
  jenkins-x.yml
Labels: size/M, updatebot

#1179 fix: build pull request broken when run_if_changed is set
  pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/master/.lighthouse/triggers/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/mybranch/.lighthouse/triggers/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/duplicate-postsubmit/.lighthouse/duplicate-lint/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/duplicate-postsubmit/.lighthouse/linter/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/duplicate-presubmit/.lighthouse/duplicate-lint/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/duplicate-presubmit/.lighthouse/linter/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/jenkins-x/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/linter/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/myrepo/.lighthouse/jenkins-x/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/myrepo/.lighthouse/linter/triggers.yaml
  pkg/triggerconfig/merge/merge.go
  pkg/triggerconfig/merge/merge_test.go
  pkg/triggerconfig/merge/test_data/simple/expected-config.yaml
  pkg/triggerconfig/merge/test_data/simple/triggers.yaml
Labels: approved, lgtm, ok-to-test, size/M

#1184 fix: remove unused error wrap
  pkg/triggerconfig/inrepo/calculate.go
Labels: approved, lgtm, ok-to-test, size/XS

#1183 fix: provide auth token early for gitea as it is required
  pkg/keeper/githubapp/factory.go
Labels: approved, lgtm, ok-to-test, size/S
