Repository jenkins-x/lighthouse, pull requests merged in 2020-01, with the labels that each got.

#441 fix: Report error status to provider if can't run metapipeline
  pkg/plumber/fake/fake.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/trigger/trigger_test.go
Labels: approved, lgtm, size/L

#438 fix: Add BBS and Gitlab test contexts
  bdd/bbs/README.md
  bdd/bbs/ci.sh
  bdd/bbs/cluster.yaml
  bdd/bbs/jx-requirements.yml
  bdd/bbs/parameters.yaml
  bdd/gitlab/README.md
  bdd/gitlab/ci.sh
  bdd/gitlab/cluster.yaml
  bdd/gitlab/jx-requirements.yml
  bdd/gitlab/parameters.yaml
  jenkins-x-bbs.yml
  jenkins-x-gitlab.yml
Labels: approved, lgtm, size/L

#448 fix: Always use latest builder-* images in BDD pipelines
  jenkins-x-bbs.yml
  jenkins-x-ghe.yml
  jenkins-x-github.yml
  jenkins-x-gitlab.yml
Labels: approved, lgtm, size/XS

#466 fix: remove the expose-controller annotations on hook and tide services
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#430 fix: compatible with kube api 1.16+
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/tide-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/S

#469 chore: Bump go-scm dependency to 1.5.70
  OWNERS
  go.mod
  go.sum
  pkg/prow/commentpruner/commentpruner.go
  pkg/prow/commentpruner/commentpruner_test.go
  pkg/prow/fakegitprovider/fakegithub.go
  pkg/prow/gitprovider/issues.go
  pkg/prow/plugins/approve/approve.go
  pkg/prow/plugins/approve/approve_test.go
  pkg/prow/plugins/blockade/blockade.go
  pkg/prow/plugins/blockade/blockade_test.go
  pkg/prow/plugins/cat/cat_test.go
  pkg/prow/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/prow/plugins/cherrypickunapproved/cherrypick-unapproved_test.go
  pkg/prow/plugins/dog/dog_test.go
  pkg/prow/plugins/help/help.go
  pkg/prow/plugins/help/help_test.go
  pkg/prow/plugins/hold/hold.go
  pkg/prow/plugins/label/label.go
  pkg/prow/plugins/label/label_test.go
  pkg/prow/plugins/lgtm/lgtm.go
  pkg/prow/plugins/lgtm/lgtm_test.go
  pkg/prow/plugins/lifecycle/close.go
  pkg/prow/plugins/lifecycle/close_test.go
  pkg/prow/plugins/lifecycle/lifecycle.go
  pkg/prow/plugins/lifecycle/lifecycle_test.go
  pkg/prow/plugins/milestonestatus/milestonestatus.go
  pkg/prow/plugins/owners-label/owners-label.go
  pkg/prow/plugins/owners-label/owners-label_test.go
  pkg/prow/plugins/pony/pony_test.go
  pkg/prow/plugins/shrug/shrug.go
  pkg/prow/plugins/sigmention/sigmention.go
  pkg/prow/plugins/sigmention/sigmention_test.go
  pkg/prow/plugins/size/size.go
  pkg/prow/plugins/size/size_test.go
  pkg/prow/plugins/stage/stage.go
  pkg/prow/plugins/stage/stage_test.go
  pkg/prow/plugins/trigger/generic-comment.go
  pkg/prow/plugins/trigger/generic-comment_test.go
  pkg/prow/plugins/trigger/pull-request.go
  pkg/prow/plugins/trigger/pull-request_test.go
  pkg/prow/plugins/trigger/trigger.go
  pkg/prow/plugins/wip/wip-label.go
  pkg/prow/plugins/wip/wip-label_test.go
  pkg/prow/plugins/yuks/yuks_test.go
Labels: approved, lgtm, size/XL

#470 fix: Use token secret like Prow does
  bdd/bbs/ci.sh
  bdd/bbs/jx-requirements.yml
  bdd/ghe/ci.sh
  bdd/ghe/jx-requirements.yml
  bdd/github/ci.sh
  bdd/github/jx-requirements.yml
  bdd/gitlab/ci.sh
  bdd/gitlab/jx-requirements.yml
  bdd/helm-requirements.yaml.template
  bdd/values.yaml.template
  charts/lighthouse/Makefile
  charts/lighthouse/templates/deployment.yaml
  charts/lighthouse/templates/oauthsecret.yaml
  charts/lighthouse/templates/tide-deployment.yaml
  charts/lighthouse/values.yaml
  jenkins-x-bbs.yml
  jenkins-x-ghe.yml
  jenkins-x-github.yml
  jenkins-x-gitlab.yml
  jenkins-x.yml
Labels: approved, lgtm, size/L

#481 fix: Rerun PipelineRuns failed due to known race conditions
  go.mod
  go.sum
  pkg/tide/githubapp/factory.go
  pkg/tide/githubapp/github_app_ctrl.go
  pkg/tide/pipelinerun_monitor.go
  pkg/tide/pipelinerun_monitor_test.go
  pkg/tide/tide.go
  pkg/tide/tide_test.go
Labels: approved, lgtm, size/L

#489 fix: Forgot to add tekton APIs to tide role
  charts/lighthouse/templates/tide-role.yaml
Labels: approved, lgtm, size/S

#493 fix: Forgot a few more permissions for the tide role
  charts/lighthouse/templates/tide-role.yaml
Labels: approved, size/XS, updatebot

#496 chore: Update BDD tests with extra log capturing
  bdd/bbs/ci.sh
  bdd/bbs/jx-requirements.yml
  bdd/ghe/ci.sh
  bdd/github/ci.sh
  bdd/gitlab/ci.sh
Labels: approved, lgtm, size/M

#509 fix: avoid nil pointer exception
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/S
