Repository jenkins-x/lighthouse, pull requests merged in 2020-09, with the labels that each got.

#1005 chore: make webhook event handlers private
  pkg/webhook/events.go
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/M

#1015 chore: Add RegisterHelpProvider method for plugins help registration
  pkg/plugins/approve/approve.go
  pkg/plugins/assign/assign.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/branchcleaner/branchcleaner.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/plugins/dog/dog.go
  pkg/plugins/help/help.go
  pkg/plugins/hold/hold.go
  pkg/plugins/hold/hold_test.go
  pkg/plugins/label/label.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lgtm/lgtm_test.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/override/override.go
  pkg/plugins/owners-label/owners-label.go
  pkg/plugins/owners-label/owners-label_test.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/size/size.go
  pkg/plugins/skip/skip.go
  pkg/plugins/stage/stage.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/plugins/trigger/pull-request_test.go
  pkg/plugins/trigger/push_test.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/welcome/welcome.go
  pkg/plugins/wip/wip-label.go
  pkg/plugins/wip/wip-label_test.go
  pkg/plugins/yuks/yuks.go
Labels: approved, lgtm, size/L

#1022 refactor: Make RegisterPlugin more declarative
  pkg/plugins/approve/approve.go
  pkg/plugins/assign/assign.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/branchcleaner/branchcleaner.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/plugins/dog/dog.go
  pkg/plugins/help/help.go
  pkg/plugins/hold/hold.go
  pkg/plugins/label/label.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/override/override.go
  pkg/plugins/owners-label/owners-label.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/size/size.go
  pkg/plugins/skip/skip.go
  pkg/plugins/stage/stage.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/welcome/welcome.go
  pkg/plugins/wip/wip-label.go
  pkg/plugins/yuks/yuks.go
Labels: approved, lgtm, size/XL

#1023 chore: replace GetXXXHandlers methods by GetPlugins
  pkg/plugins/plugins.go
  pkg/webhook/events.go
Labels: approved, lgtm, size/L

#1024 refactor: manage commands in Plugin descriptor
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/assign/assign.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cat/cat_test.go
  pkg/plugins/dog/dog.go
  pkg/plugins/dog/dog_test.go
  pkg/plugins/help/help.go
  pkg/plugins/help/help_test.go
  pkg/plugins/hold/hold.go
  pkg/plugins/hold/hold_test.go
  pkg/plugins/label/label.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestone/milestone_test.go
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/milestonestatus/milestonestatus_test.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony.go
  pkg/plugins/pony/pony_test.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/skip/skip.go
  pkg/plugins/stage/stage.go
  pkg/plugins/stage/stage_test.go
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/yuks/yuks.go
  pkg/plugins/yuks/yuks_test.go
  pkg/webhook/events.go
Labels: approved, lgtm, size/XXL

#1027 refactor: synthesize plugin help provider based on plugin definition
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/assign/assign.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/blockade/blockade_test.go
  pkg/plugins/branchcleaner/branchcleaner.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cherrypickunapproved/cherrypick-unapproved.go
  pkg/plugins/dog/dog.go
  pkg/plugins/help/help.go
  pkg/plugins/hold/hold.go
  pkg/plugins/label/label.go
  pkg/plugins/label/label_test.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lgtm/lgtm_test.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/override/override.go
  pkg/plugins/owners-label/owners-label.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/size/size.go
  pkg/plugins/size/size_test.go
  pkg/plugins/skip/skip.go
  pkg/plugins/stage/stage.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/trigger/trigger_test.go
  pkg/plugins/updateconfig/updateconfig.go
  pkg/plugins/welcome/welcome.go
  pkg/plugins/welcome/welcome_test.go
  pkg/plugins/wip/wip-label.go
  pkg/plugins/yuks/yuks.go
Labels: approved, lgtm, size/L

#1028 feat: Set Keeper status desc for green PRs blocked by retests
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
  pkg/keeper/status.go
  pkg/keeper/status_test.go
Labels: approved, lgtm, size/L

#1030 chore: make plugin name private in approve blockade and wip plugins
  pkg/plugins/approve/approve.go
  pkg/plugins/blockade/blockade.go
  pkg/plugins/blockade/blockade_test.go
  pkg/plugins/wip/wip-label.go
Labels: approved, lgtm, size/S

#1031 refactor: dog plugin
  pkg/plugins/dog/dog.go
  pkg/plugins/dog/dog_test.go
  pkg/plugins/plugins.go
Labels: approved, lgtm, size/L

#1036 refactor: milestonestatus plugin
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/milestonestatus/milestonestatus_test.go
Labels: approved, lgtm, size/M

#1039 refactor: label plugin
  pkg/plugins/label/label.go
  pkg/plugins/label/label_test.go
Labels: approved, lgtm, size/L

#1042 refactor: help plugin
  pkg/plugins/help/help.go
  pkg/plugins/help/help_test.go
  pkg/plugins/plugins.go
Labels: approved, lgtm, size/M

#1045 refactor: assign plugin
  pkg/plugins/assign/assign.go
  pkg/plugins/assign/assign_test.go
Labels: approved, lgtm, size/M

#1046 refactor: lifecycle plugin
  pkg/plugins/lifecycle/close.go
  pkg/plugins/lifecycle/close_test.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/lifecycle/lifecycle_test.go
  pkg/plugins/lifecycle/reopen.go
  pkg/plugins/lifecycle/reopen_test.go
Labels: approved, lgtm, size/L

#1047 refactor: lgtm plugin
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lgtm/lgtm_test.go
Labels: approved, lgtm, size/M

#1038 refactor: milestone plugin
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestone/milestone_test.go
Labels: approved, lgtm, size/M

#1049 refactor: override plugin
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
Labels: approved, lgtm, size/L

#1052 refactor: trigger plugin
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/trigger.go
Labels: approved, lgtm, size/M

#1050 refactor: hold plugin
  pkg/plugins/hold/hold.go
  pkg/plugins/hold/hold_test.go
Labels: approved, lgtm, size/M

#1051 refactor: sigmention plugin
  pkg/plugins/dog/dog_test.go
  pkg/plugins/label/label_test.go
  pkg/plugins/milestonestatus/milestonestatus_test.go
  pkg/plugins/override/override_test.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony_test.go
  pkg/plugins/shrug/shurg_test.go
  pkg/plugins/sigmention/sigmention.go
  pkg/plugins/stage/stage_test.go
  pkg/plugins/yuks/yuks_test.go
  pkg/webhook/events.go
Labels: approved, lgtm, size/M

#1054 fix: Actually enable the milestone plugin.
  pkg/plugins/milestone/milestone.go
  pkg/scmprovider/client.go
  pkg/scmprovider/fake/fake.go
  pkg/scmprovider/legacy_helpers.go
  pkg/scmprovider/milestones.go
Labels: approved, lgtm, size/L

#1055 refactor: refactor the plugin command system
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/assign/assign.go
  pkg/plugins/assign/assign_test.go
  pkg/plugins/cat/cat.go
  pkg/plugins/cat/cat_test.go
  pkg/plugins/command.go
  pkg/plugins/command_test.go
  pkg/plugins/dog/dog.go
  pkg/plugins/dog/dog_test.go
  pkg/plugins/help/help.go
  pkg/plugins/help/help_test.go
  pkg/plugins/hold/hold.go
  pkg/plugins/hold/hold_test.go
  pkg/plugins/label/label.go
  pkg/plugins/label/label_test.go
  pkg/plugins/lgtm/lgtm.go
  pkg/plugins/lgtm/lgtm_test.go
  pkg/plugins/lifecycle/close_test.go
  pkg/plugins/lifecycle/lifecycle.go
  pkg/plugins/lifecycle/lifecycle_test.go
  pkg/plugins/lifecycle/reopen.go
  pkg/plugins/lifecycle/reopen_test.go
  pkg/plugins/milestone/milestone.go
  pkg/plugins/milestone/milestone_test.go
  pkg/plugins/milestonestatus/milestonestatus.go
  pkg/plugins/milestonestatus/milestonestatus_test.go
  pkg/plugins/override/override.go
  pkg/plugins/override/override_test.go
  pkg/plugins/plugins.go
  pkg/plugins/pony/pony.go
  pkg/plugins/pony/pony_test.go
  pkg/plugins/shrug/shrug.go
  pkg/plugins/shrug/shrug_test.go
  pkg/plugins/skip/skip.go
  pkg/plugins/stage/stage.go
  pkg/plugins/stage/stage_test.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/plugins/trigger/trigger.go
  pkg/plugins/yuks/yuks.go
  pkg/plugins/yuks/yuks_test.go
  pkg/webhook/events.go
Labels: approved, lgtm, size/XXL

#1056 feat: add scm providers exclusion support to plugins
  pkg/pluginhelp/pluginhelp.go
  pkg/plugins/plugin.go
  pkg/plugins/plugin_test.go
  pkg/plugins/plugins.go
  pkg/webhook/events.go
Labels: approved, lgtm, size/L

#1062 fix: make welcome plugin work
  pkg/plugins/welcome/welcome.go
  pkg/plugins/welcome/welcome_test.go
  pkg/scmprovider/client.go
  pkg/scmprovider/pull_requests.go
Labels: approved, lgtm, size/M

#1067 chore: remove obsolete plugins code
  pkg/plugins/plugins.go
Labels: approved, lgtm, size/S

#1068 docs: Update plugins.yaml to add trigger plugin
  docs/INSTALL.md
Labels: approved, lgtm, ok-to-test, size/XS

#1071 fix: avoid processing the main branch twice
  pkg/triggerconfig/inrepo/calculate.go
Labels: approved, lgtm, size/XS

#1072 fix: merging postsubmits & presubmits together by name to avoid duplicates
  pkg/triggerconfig/inrepo/calculate_test.go
  pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/master/.lighthouse/triggers/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/branchtest/refs/mybranch/.lighthouse/triggers/triggers.yaml
  pkg/triggerconfig/merge/merge.go
Labels: approved, lgtm, size/M

#1080 fix: run as an unprivileged user
  charts/lighthouse/templates/gc-jobs-cj.yaml
  docker/foghorn/Dockerfile
  docker/gc/Dockerfile
  docker/jenkins/Dockerfile
  docker/keeper/Dockerfile
  docker/tekton/Dockerfile
  docker/webhooks/Dockerfile
Labels: approved, lgtm, ok-to-test, size/M

#1081 fix: use numeric user for the image
  docker/foghorn/Dockerfile
  docker/gc/Dockerfile
  docker/jenkins/Dockerfile
  docker/keeper/Dockerfile
  docker/tekton/Dockerfile
  docker/webhooks/Dockerfile
Labels: approved, lgtm, ok-to-test, size/S

#1087 fix: bigger default memory limit for webhooks
  charts/lighthouse/README.md
  charts/lighthouse/values.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1086 fix: add more fields to webhook chart deployment
  charts/lighthouse/README.md
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, ok-to-test, size/S
