Repository jenkins-x/lighthouse, pull requests merged in 2021-06, with the labels that each got.

#1321 fix: allow the trigger disable to be per repo
  pkg/keeper/keeper.go
Labels: approved, size/XS

#1319 fix: chart syntax errors
  charts/lighthouse/templates/jenkins-controller-deployment.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1317 chore: fix a minor typo
  pkg/keeper/keeper.go
Labels: approved, size/XS

#1320 chore: bump the image tag from 0.0.750 to 1.1.0
  .lighthouse/jenkins-x/release.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, ok-to-test, size/S

#1323 fix: lets add a nicer default name for LighthouseJobs
  pkg/engines/tekton/test_data/controller/start-batch-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-push/expected-pr.yml
  pkg/engines/tekton/utils.go
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
  pkg/webhook/create_agent.go
Labels: approved, size/L

#1324 fix(keeper): use the target URL when updating status
  pkg/keeper/status.go
Labels: approved, lgtm, ok-to-test, size/XS

#1326 fix: caching bug for release branches
  pkg/filebrowser/git_file_browser.go
Labels: approved, size/XS
