Repository jenkins-x/lighthouse, pull requests merged in 2021-07, with the labels that each got.

#1333 chore: fix updatebot
  .jx/updatebot.yaml
Labels: approved, size/XS

#1329 fix: config-updater not work with gitlab
  pkg/plugins/updateconfig/updateconfig.go
  pkg/webhook/events.go
Labels: approved, lgtm, ok-to-test, size/XS

#1335 fix: avoid double agent + git fetch on push hooks
  pkg/webhook/events.go
Labels: approved, size/S

#1336 fix: make configAgent creation async
  charts/lighthouse/README.md
  pkg/webhook/create_agent.go
  pkg/webhook/events.go
Labels: approved, size/L

#1337 fix: avoid unnecessary fetch if we have a sha locally already
  pkg/filebrowser/git_file_browser.go
  pkg/filebrowser/git_file_browser_test.go
  pkg/git/v2/interactor.go
Labels: approved, size/M

#1338 fix: allow external plugins to be disabled
  charts/lighthouse/templates/config-external-plugins.yaml
  charts/lighthouse/values.yaml
  pkg/externalplugincfg/load.go
  pkg/externalplugincfg/load_test.go
  pkg/externalplugincfg/types.go
  pkg/foghorn/controller.go
  pkg/util/externalplugins.go
  pkg/util/externalplugins_test.go
  pkg/util/strings.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: approved, size/L

#1339 fix: allow webhooks to view services
  charts/lighthouse/templates/webhooks-role.yaml
Labels: approved, size/XS

#1342 fix: correct BBC scm client authentication for keeper
  pkg/keeper/githubapp/factory.go
Labels: approved, lgtm, ok-to-test, size/XS

#1340 fix: remove the old go-scm based file browser
  pkg/config/job/base.go
  pkg/externalplugincfg/load.go
  pkg/externalplugincfg/load_test.go
  pkg/filebrowser/fake/fake_file_browser.go
  pkg/filebrowser/git_file_browser.go
  pkg/filebrowser/git_file_browser_test.go
  pkg/filebrowser/interface.go
  pkg/filebrowser/scm_file_browser.go
  pkg/filebrowser/scm_provider_client.go
  pkg/git/v2/client_factory.go
  pkg/gittest/helpers.go
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
  pkg/keeper/githubapp/factory.go
  pkg/keeper/keeper.go
  pkg/keeper/keeper_test.go
  pkg/plugins/override/override.go
  pkg/plugins/trigger/push.go
  pkg/plugins/trigger/trigger.go
  pkg/repoowners/repoowners_test.go
  pkg/triggerconfig/inrepo/calculate_test.go
  pkg/triggerconfig/inrepo/load_integration_test.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/load_triggers.go
  pkg/triggerconfig/inrepo/load_triggers_test.go
  pkg/webhook/create_agent_integration_test.go
  pkg/webhook/webhook.go
Labels: approved, size/XL

#1346 fix: Bit Bucket Cloud requires a valid URL in all status reports
  pkg/keeper/status.go
Labels: approved, lgtm, ok-to-test, size/XS

#1349 fix: add webhook poller
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Makefile
  charts/lighthouse/templates/_helpers.tpl
  charts/lighthouse/templates/poller-deployment.yaml
  charts/lighthouse/templates/poller-rb.yaml
  charts/lighthouse/templates/poller-role.yaml
  charts/lighthouse/templates/poller-sa.yaml
  charts/lighthouse/values.yaml
  cmd/poller/main.go
  cmd/webhooks/main.go
  docker/poller/Dockerfile
  pkg/poller/poller.go
  pkg/poller/poller_test.go
  pkg/poller/pollstate/interface.go
  pkg/poller/pollstate/memory.go
  pkg/poller/test_data/myorg/myrepo/README.md
  pkg/triggerconfig/inrepo/calculate_test.go
  pkg/triggerconfig/inrepo/load_integration_test.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/load_triggers_test.go
  pkg/triggerconfig/merge/merge_test.go
  pkg/webhook/create_agent_integration_test.go
  pkg/webhook/webhook.go
Labels: approved, size/XXL

#1350 fix: support hmac signature on the poller
  charts/lighthouse/templates/poller-deployment.yaml
  charts/lighthouse/values.yaml
  cmd/poller/main.go
  pkg/util/hmac.go
  pkg/util/hmac_test.go
  pkg/webhook/webhook.go
Labels: approved, size/M

#1351 fix: listen on http port
  cmd/poller/main.go
  pkg/poller/poller.go
Labels: approved, size/S

#1352 fix: improve support for private git repos
  cmd/poller/main.go
  pkg/git/v2/client_factory.go
  pkg/git/v2/remote.go
Labels: approved, size/M

#1353 fix: avoid git mirroring and fix detecting of new releases
  cmd/poller/main.go
  pkg/filebrowser/git_file_browser.go
  pkg/git/v2/interactor.go
  pkg/git/v2/no_mirror_client_factory.go
  pkg/poller/poller.go
  pkg/webhook/webhook.go
Labels: approved, size/L

#1347 fix: add a new require_run property
  pkg/config/job/presubmit.go
  pkg/triggerconfig/inrepo/load_triggers_test.go
Labels: approved, size/XS

#1355 chore: regen docs
  docs/config/jobs/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/trigger/github-com-jenkins-x-lighthouse-pkg-config-job.md
Labels: approved, size/XS

#1356 chore: temporary disable of require run property
  pkg/config/job/presubmit.go
Labels: approved, size/XS

#1358 fix: pipeline lint when multiple pipelinerun.spec.workspaces exist
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/default_parameters_test.go
Labels: approved, size/M

#1359 chore: tone down some of the logging else it appears in the terminal …
  pkg/filebrowser/git_file_browser.go
  pkg/git/v2/client_factory.go
  pkg/git/v2/no_mirror_client_factory.go
Labels: approved, size/S

#1360 chore: more verbose info to debug logging
  pkg/config/job/base.go
  pkg/filebrowser/git_file_browser.go
  pkg/git/v2/interactor.go
Labels: approved, size/S
