Repository jenkins-x/lighthouse, pull requests merged in 2021-03, with the labels that each got.

#1260 fix: handle v1 CRDs
  charts/lighthouse/README.md
  charts/lighthouse/config/lighthousejobs.lighthouse.jenkins.io-v1.yaml
  charts/lighthouse/templates/lighthousejobs-crd.yaml
Labels: approved, lgtm, size/M

#1259 fix: helm chart webhook pod annotations
  charts/lighthouse/templates/webhooks-deployment.yaml
Labels: approved, ok-to-test, size/XS

#1263 fix: better validation of uses pipelines
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/params.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/task/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-all-steps/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-custom-param-task/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-custom-param/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-add-custom-explict/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-add-custom/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-explicit/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-multiple-copies/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-override-resources/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-override/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-version-stream/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-task-and-steps/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected2.yaml
  pkg/triggerconfig/inrepo/uses_resolver.go
Labels: approved, size/XL

#1264 fix: add default workspace binding if none are provided when using tasks
  .jx/updatebot.yaml
  pkg/triggerconfig/inrepo/params.go
  pkg/triggerconfig/inrepo/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/tasks/git-clone/git-clone.yaml
  pkg/triggerconfig/inrepo/test_data/jenkins-x/jx3-pipeline-catalog/refs/myversionstreamref/tasks/maven-java11/release.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-task-and-steps/expected.yaml
Labels: approved, size/M

#1265 fix: add missing workspace bindings
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/params.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-task-and-steps/expected.yaml
Labels: approved, size/S

#1266 fix: add missing PipelineRunParams when creating LighthouseJobSpec from job.Base
  .lighthouse/jenkins-x/release.yaml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/expected-pr.yml
  pkg/engines/tekton/test_data/controller/start-pullrequest/observed-lhjob.yml
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
Labels: approved, size/M

#1267 fix: upgrade go-scm
  go.mod
  go.sum
Labels: approved, size/XS
