Repository jenkins-x/lighthouse, pull requests merged in 2021-04, with the labels that each got.

#1270 chore: to improve kick the tyres experience and reduce the barrier to…
  go.sum
  pkg/plugins/approve/approve.go
  pkg/plugins/trigger/generic-comment.go
Labels: approved, lgtm, size/S

#1273 fix: include tags when fetching updates from the server
  pkg/filebrowser/git_file_browser_test.go
  pkg/git/v2/interactor.go
  pkg/git/v2/interactor_test.go
Labels: approved, lgtm, ok-to-test, size/M

#1274 fix: add flag to disable uses cache
  go.sum
  pkg/triggerconfig/inrepo/uses_resolver.go
Labels: approved, size/S

#1275 fix: log at warning level when external plugin failed
  pkg/util/externalplugins.go
Labels: approved, lgtm, ok-to-test, size/XS

#1277 fix: add regex to exclude changed files from triggering a release
  docs/config/jobs/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/trigger/github-com-jenkins-x-lighthouse-pkg-config-job.md
  pkg/config/job/regexpchangematcher.go
  pkg/config/job/regexpchangematcher_test.go
  pkg/git/v2/interactor.go
  pkg/git/v2/interactor_test.go
Labels: approved, lgtm, size/L

#1278 fix: add retry around updating the LighthouseJob status
  pkg/foghorn/controller.go
Labels: approved, size/M

#1279 fix: lets not fail if a repo has no triggers dir
  go.sum
  pkg/filebrowser/fake/fake_file_browser.go
  pkg/filebrowser/git_file_browser.go
  pkg/triggerconfig/inrepo/load_triggers.go
  pkg/triggerconfig/inrepo/load_triggers_test.go
  pkg/triggerconfig/inrepo/test_data/empty_dir/README.md
Labels: approved, lgtm, size/M

#1280 fix: use jenkins-x chatops doc link instead of the original prow one
  pkg/plugins/approve/approve_test.go
  pkg/plugins/approve/approvers/approvers_test.go
  pkg/plugins/approve/approvers/owners.go
  pkg/plugins/trigger/pull-request.go
Labels: approved, lgtm, ok-to-test, size/M

#1284 fix: use the right event GUID when handling comments
  pkg/webhook/events.go
Labels: approved, lgtm, ok-to-test, size/XS

#1289 fix: preserve sidecars with in repo pipelines
  go.sum
  pkg/triggerconfig/inrepo/params.go
  pkg/triggerconfig/inrepo/test_data/jenkins-x/jx3-pipeline-catalog/refs/1d39235ee9235d7d52d4025a8e59cb8bda04306a/packs/javascript-selenium/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-inherit-sidecar/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar/source.yaml
  pkg/triggerconfig/inrepo/uses_resolver.go
Labels: approved, lgtm, size/XL

#1298 fix: improve logging
  charts/lighthouse/README.md
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/jenkins-controller-deployment.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/tekton-controller-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
  go.sum
  pkg/logrusutil/logrusutil.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-custom-git/expected.yaml
Labels: approved, size/L

#1300 chore: remove typo
  charts/lighthouse/values.yaml
Labels: approved, size/XS
