Repository jenkins-x/lighthouse, pull requests merged in 2021-02, with the labels that each got.

#1229 chore: tone down logging to debug level
  pkg/git/v2/interactor.go
Labels: approved, lgtm, size/S

#1233 fix: prometheus support for keeper
  charts/lighthouse/README.md
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
  cmd/keeper/main.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, ok-to-test, size/M

#1228 chore: add GitHub action to run markdown link check
  .github/workflows/pull-request.yml
Labels: needs-ok-to-test, size/S

#1223 chore: fix the wrong link of https://bitbucket.org
  README.md
Labels: needs-ok-to-test, size/XS

#1226 fix: add exception handle for scm response body
  pkg/scmprovider/issues.go
Labels: approved, lgtm, ok-to-test, size/M

#1237 chore: try fix markdown link checker
  .github/workflows/.mlc_config.json
  .github/workflows/pull-request.yml
Labels: size/S

#1235 fix: in uses resolver, clone pipelinerun when returning from the cache to avoid changes persistng between evaluations
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/common.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/expected2.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-ussue-1234/source2.yaml
  pkg/triggerconfig/inrepo/uses_resolver.go
Labels: approved, lgtm, ok-to-test, size/L

#1246 fix: remove the old draft labels
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/jenkins-controller-deployment.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/tekton-controller-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/templates/webhooks-ingress.yaml
Labels: approved, lgtm, size/S

#1247 fix: allow axtra labels to be added to a webhook deployment
  charts/lighthouse/README.md
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/XS

#1248 fix: polish go dependencies
  go.mod
  go.sum
Labels: size/M

#1249 chore: add more logging
  pkg/keeper/keeper.go
Labels: approved, lgtm, size/XS
