Repository jenkins-x/lighthouse, pull requests merged in 2021-12, with the labels that each got.

#1395 feat: Use OWNERS_ALIASES files from other repos
  pkg/repoowners/repoowners.go
  pkg/repoowners/repoowners_test.go
Labels: size/M, approved, ok-to-test

#1401 feat: Add ingress class name and upgrade to stable ingress
  charts/lighthouse/README.md
  charts/lighthouse/templates/webhooks-ingress.yaml
  charts/lighthouse/values.yaml
Labels: size/S, approved, ok-to-test

#1402 feat: Add backoff limit for cron job
  charts/lighthouse/README.md
  charts/lighthouse/templates/gc-jobs-cj.yaml
  charts/lighthouse/values.yaml
Labels: size/XS, approved, lgtm, ok-to-test

#1399 feat: Support poller release and pull request periods
  charts/lighthouse/values.yaml
  cmd/poller/main.go
  pkg/poller/poller.go
Labels: size/M, approved, lgtm, ok-to-test

#1406 feat: Improve poll flag and env var descriptions
  charts/lighthouse/values.yaml
  cmd/poller/main.go
Labels: size/S, approved, lgtm, ok-to-test

#1407 fix: keep group in lj label for nested gitlab repos
  pkg/jobutil/jobutil.go
  pkg/jobutil/jobutil_test.go
  pkg/plugins/trigger/trigger.go
Labels: size/L, approved
