Repository jenkins-x/lighthouse, pull requests merged in 2021-01, with the labels that each got.

#1192 fix: return the err to prevent a panic below when client.repoClient is nil
  pkg/filebrowser/git_file_browser.go
Labels: approved, lgtm, ok-to-test, size/XS

#1194 fix: convert old incorrect configuration
  pkg/triggerconfig/inrepo/load_integration_test.go
  pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/jenkins-x/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/loadtest/.lighthouse/linter/triggers.yaml
  pkg/triggerconfig/merge/merge.go
Labels: approved, lgtm, size/S

#1196 feat: allow user to specify pod annotations for gc job
  charts/lighthouse/templates/gc-jobs-cj.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1203 feat: allow in-repo triggers to specify a URL for the source so we can easily trigger remote managed pipeline definitions
  go.mod
  go.sum
  pkg/triggerconfig/inrepo/load_integration_test.go
  pkg/triggerconfig/inrepo/load_triggers.go
  pkg/triggerconfig/inrepo/load_triggers_test.go
  pkg/triggerconfig/inrepo/test_data/load_url/foo.yaml
Labels: approved, lgtm, size/L

#1197 fix: size plugin - check patch for backup size
  pkg/plugins/size/size.go
Labels: approved, lgtm, ok-to-test, size/S

#1213 fix: allow labels like Approved by making comparision in lower case
  pkg/plugins/approve/approve.go
Labels: approved, lgtm, ok-to-test, size/XS

#1214 Fix/case sensitive approved tag
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#1216 fix: keeper status case insensitive labels
  pkg/keeper/status.go
  pkg/keeper/status_test.go
Labels: approved, lgtm, ok-to-test, size/S

#1217 fix: get annotations as from jobutil.LabelsAndAnnotations
  pkg/jobutil/jobutil.go
Labels: approved, lgtm, ok-to-test, size/XS

#1221 fix: correct chart values indentation for foghorn.resources.requests
  charts/lighthouse/README.md
  charts/lighthouse/values.yaml
Labels: approved, lgtm, ok-to-test, size/S
