Repository jenkins-x/lighthouse, pull requests merged in 2021-08, with the labels that each got.

#1368 fix: create both CRDs properly
  charts/lighthouse/templates/lighthousebreakpoints-crd.yaml
  charts/lighthouse/templates/lighthousejobs-crd.yaml
Labels: size/S, approved

#1364 fix: fall back to commit.sha if commit.Tree.sha is empty
  pkg/plugins/lgtm/lgtm.go
Labels: size/S, approved, ok-to-test

#1366 chore: fix typo in tekton quickstart.
  docs/install_lighthouse_with_tekton.md
Labels: size/M, needs-ok-to-test

#1371 fix: better support for pipeline branch names
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/test_data/controller/debug-pr/expected-lhjob.yml
  pkg/engines/tekton/test_data/controller/debug-pr/expected-pr.yml
  pkg/engines/tekton/test_data/controller/debug-pr/observed-lhjob.yml
  pkg/engines/tekton/utils.go
Labels: size/M, approved

#1372 fix: handle validation errors with alpha syntax
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar-ws/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar-ws/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-steps-with-sidecar-ws/source.yaml
Labels: size/L, approved
