Repository jenkins-x/lighthouse, pull requests merged in 2021-05, with the labels that each got.

#1305 chore: ensure opentelemetry annotations are not copied
  pkg/jobutil/jobutil.go
Labels: approved, lgtm, ok-to-test, size/XS

#1307 fix: fix uses resolver using incorrect version of uses:task.yaml
  go.sum
  pkg/triggerconfig/inrepo/calculate_test.go
  pkg/triggerconfig/inrepo/resolver_cache.go
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/shared-task.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/master/.lighthouse/jenkins-x/triggers.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/pullrequest.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/shared-task.yaml
  pkg/triggerconfig/inrepo/test_data/myorg/issue-1306/refs/pr1/.lighthouse/jenkins-x/triggers.yaml
  pkg/triggerconfig/inrepo/uses_resolver.go
Labels: approved, lgtm, ok-to-test, size/L

#1310 chore: upgrade go-scm to 1.9.0
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#1308 fix: fix typo by renaming uses-ussue-1234 to uses-issue-1234
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/common.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/expected2.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/source.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/uses-issue-1234/source2.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#1312 fix: add optional proxy env vars
  charts/lighthouse/templates/webhooks-deployment.yaml
Labels: approved, size/XS

#1314 fix: add optional proxy env vars
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/tekton-controller-deployment.yaml
Labels: approved, size/XS

#1311 fix: handling draft PRs without errors
  pkg/webhook/events.go
Labels: approved, lgtm, ok-to-test, size/XS

#1316 chore: move from google container registry to github packages
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/lighthouse/README.md
  charts/lighthouse/values.yaml
Labels: approved, lgtm, size/M
