Repository jenkins-x/lighthouse, pull requests merged in 2022-10, with the labels that each got.

#1490 fix: Set log level in chart
  charts/lighthouse/README.md
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/gc-jobs-cj.yaml
  charts/lighthouse/templates/jenkins-controller-deployment.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/poller-deployment.yaml
  charts/lighthouse/templates/tekton-controller-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
  pkg/config/lighthouse/config.go
Labels: size/L, approved

#1489 feat: adding pod labels in webhooks
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
Labels: size/XS, approved, ok-to-test

#1493 feat: Bump go-scm to v1.11.32
  go.mod
  go.sum
Labels: size/S, approved, ok-to-test

#1491 fix: Correct / update docs
  Makefile
  charts/lighthouse/templates/plugins-cm.yaml
  crds/lighthouse.jenkins.io_lighthousebreakpoints.yaml
  crds/lighthouse.jenkins.io_lighthousejobs.yaml
  docs/config/jobs/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/config/jobs/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/config/jobs/k8s-io-api-core-v1.md
  docs/config/jobs/k8s-io-apimachinery-pkg-apis-meta-v1.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-keeper.md
  docs/config/lighthouse/github-com-jenkins-x-lighthouse-pkg-config-lighthouse.md
  docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md
  docs/crds/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/crds/k8s-io-api-core-v1.md
  docs/crds/k8s-io-apimachinery-pkg-apis-meta-v1.md
  docs/plugins/Plugins config.md
  docs/trigger/github-com-jenkins-x-lighthouse-pkg-config-job.md
  docs/trigger/github-com-tektoncd-pipeline-pkg-apis-pipeline-v1beta1.md
  docs/trigger/k8s-io-api-core-v1.md
  docs/trigger/k8s-io-apimachinery-pkg-apis-meta-v1.md
  hack/go.mod
  hack/go.sum
  pkg/foghorn/controller_test.go
  pkg/plugins/config.go
  pkg/triggerconfig/merge/test_data/simple/expected-plugins.yaml
  pkg/triggerconfig/merge/test_data/simple/source-plugins.yaml
  pkg/webhook/test_data/test_plugins.yaml
  test/e2e/jenkins/test_data/example-plugins.tmpl.yml
  test/e2e/tekton/test_data/example-plugins.tmpl.yml
Labels: size/XXL, approved

#1502 Support GitLab nested groups
  pkg/git/git.go
Labels: size/XS, approved, ok-to-test

#1503 fix: Make release work
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1504 Revert "fix: Make release work"
  .lighthouse/jenkins-x/release.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/poller-deployment.yaml
Labels: size/S, approved

#1506 Replace `io/ioutil` with `io` and `os` packages
  cmd/jenkins/main.go
  cmd/poller/main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/secret/secret.go
  pkg/engines/jenkins/client.go
  pkg/engines/tekton/activity_test.go
  pkg/engines/tekton/controller_test.go
  pkg/filebrowser/fake/fake_file_browser.go
  pkg/filebrowser/git_file_browser.go
  pkg/filebrowser/git_file_browser_test.go
  pkg/foghorn/controller_test.go
  pkg/git/git.go
  pkg/git/localgit/localgit.go
  pkg/git/v2/client_factory.go
  pkg/git/v2/no_mirror_client_factory.go
  pkg/interrupts/interrupts_test.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/cat/cat.go
  pkg/plugins/plugins.go
  pkg/plugins/updateconfig/updateconfig_test.go
  pkg/plugins/welcome/welcome_test.go
  pkg/repoowners/repoowners.go
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/load_pipelinerun_test.go
  pkg/triggerconfig/inrepo/load_triggers.go
  pkg/triggerconfig/inrepo/uses_resolver.go
  pkg/triggerconfig/merge/merge_test.go
  pkg/util/externalplugins.go
  pkg/util/githubapp.go
  pkg/util/owner_tokens_dir.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
  test/e2e/helpers.go
  test/e2e/jenkins/helper.go
  test/e2e/jenkins/jenkins_test.go
  test/e2e/tekton/tekton_test.go
  test/e2e/util/copy.go
Labels: size/L, approved, ok-to-test

#1508 refactor: remove breakpoint code from lighthouse
  cmd/tektoncontroller/main.go
  pkg/engines/tekton/controller.go
  pkg/engines/tekton/controller_test.go
  pkg/engines/tekton/utils.go
  pkg/watcher/breakpoint_watcher.go
  pkg/watcher/breakpoint_watcher_test.go
Labels: size/L, approved

#1507 fix: add missing params to tekton pipelinerun 'finally'
  pkg/triggerconfig/inrepo/default_parameters.go
  pkg/triggerconfig/inrepo/default_parameters_test.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-params/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-params/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-params/source.yaml
Labels: size/L, approved, ok-to-test
