Repository jenkins-x/lighthouse, pull requests merged in 2022-04, with the labels that each got.

#1439 fix: added some extra metrics and a warning for any users having problems with lighthouse
  OWNERS
  pkg/keeper/keeper.go
Labels: size/S, approved

#1441 refactor: upgrade to go 1.17
  go.mod
  go.sum
Labels: size/M, approved

#1442 fix: Fix poller Git client deadlock
  pkg/filebrowser/git_file_browser.go
Labels: size/XS, approved, lgtm, ok-to-test
