Repository jenkins-x/lighthouse, pull requests merged in 2022-11, with the labels that each got.

#1510 chore: processUsesSteps now handle ps.Finally tasks too
  pkg/triggerconfig/inrepo/load_pipelinerun.go
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/README.md
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/common.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/expected.yaml
  pkg/triggerconfig/inrepo/test_data/load_pipelinerun/pipeline-finally-uses/source.yaml
Labels: size/L, approved, ok-to-test

#1509 chore: upgrade tektoncd pipeline to 0.33.4
  go.mod
  go.sum
Labels: size/L, approved

#1512 feat: allow use of existing git token and HMAC token secrets
  charts/lighthouse/README.md
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/hmacsecret.yaml
  charts/lighthouse/templates/keeper-deployment.yaml
  charts/lighthouse/templates/oauthsecret.yaml
  charts/lighthouse/templates/poller-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
Labels: size/M, approved, ok-to-test

#1514 feat: Add support for HMAC token volume
  charts/lighthouse/templates/foghorn-deployment.yaml
  charts/lighthouse/templates/poller-deployment.yaml
  charts/lighthouse/templates/webhooks-deployment.yaml
  charts/lighthouse/values.yaml
  cmd/poller/main.go
  pkg/util/scmclient.go
  pkg/util/scmclient_test.go
  pkg/util/test_data/secret_dir/hmac-token
Labels: size/L, approved, ok-to-test

#1515 chore: upgrade tekton 0.35.1
  go.mod
  go.sum
Labels: size/XXL, approved
