Repository jenkins-x/lighthouse, pull requests merged in 2022-09, with the labels that each got.

#1473 feat: add default merge type to config.go
  cmd/keeper/config.md
  pkg/config/keeper/config.go
  pkg/config/lighthouse/config.go
Labels: size/S, approved

#1463 fix: evaluate ignoreChanges before checking if pre-submit should always run
  Makefile
  pkg/config/job/config.go
  pkg/config/job/presubmit.go
  pkg/jobutil/filter.go
  pkg/plugins/trigger/generic-comment.go
Labels: size/M, approved

#1477 chore: upgrade tektoncd pipeline module to 0.32.4
  go.mod
  go.sum
Labels: approved, size/XL

#1487 fix: Errorf does not support error-wrapping
  go.mod
  go.sum
Labels: size/XS, approved

#1488 fix: change checks to see if comment event is from PR
  go.mod
  go.sum
  pkg/webhook/create_agent.go
  pkg/webhook/events.go
Labels: size/M, approved
