Repository jenkins-x/lighthouse, pull requests merged in 2023-03, with the labels that each got.

#1519 refactor: Update alpine base image to 3.17
  docker/foghorn/Dockerfile
  docker/gc/Dockerfile
  docker/jenkins/Dockerfile
  docker/keeper/Dockerfile
  docker/poller/Dockerfile
  docker/tekton/Dockerfile
  docker/webhooks/Dockerfile
Labels: size/S, approved, ok-to-test

#1525 feat: make approve plugin ignore PRs with label updatebot
  pkg/labels/labels.go
  pkg/plugins/approve/approve.go
  pkg/plugins/config.go
Labels: size/S, approved

#1445 chore: add tls option on webhooks ingress
  charts/lighthouse/templates/webhooks-ingress.yaml
  charts/lighthouse/values.yaml
Labels: size/S, approved, lgtm, ok-to-test

#1529 chore: upgrade jx changelog pipeline version
  .lighthouse/jenkins-x/release.yaml
Labels: size/XS, approved

#1530 fix: use jx-boot image for changelog
  .lighthouse/jenkins-x/release.yaml
Labels: size/S, approved
