Repository jenkins-x/lighthouse, pull requests merged in 2025-01, with the labels that each got.

#1633 chore: this warning isn't actionable (I think) so let's remove it until it is
  pkg/plugins/trigger/pull-request.go
Labels: size/S, approved, ok-to-test

#1619 fix: retry creation of pipelinerun
  pkg/engines/tekton/controller.go
Labels: size/XS, approved

#1636 revert: retry creation of pipelinerun
  pkg/engines/tekton/controller.go
Labels: size/XS, approved

#1637 chore(deps): update go-scm
  go.mod
  go.sum
  pkg/keeper/keeper_test.go
  pkg/plugins/trigger/periodic.go
  pkg/scmprovider/content.go
Labels: size/S, approved

#1639 chore: Tweak APPROVALNOTIFIER markdown template to render consistent HTML
  pkg/plugins/approve/approve_test.go
  pkg/plugins/approve/approvers/approvers_test.go
  pkg/plugins/approve/approvers/owners.go
Labels: size/M, approved, ok-to-test

#1641 feat: allow display report completion duration
  docs/config/plugins/github-com-jenkins-x-lighthouse-pkg-plugins.md
  docs/plugins/Plugins config.md
  pkg/foghorn/controller.go
  pkg/plugins/config.go
Labels: size/M, approved, ok-to-test
